EmbedWrapper.js
embed.js
helpers.js
image-embed.js
package.json
yarn.lock

It seems there isn't a simple way for node views to subscribe to global state changes. In fact as marijn says [here](https://discuss.prosemirror.net/t/setting-up-a-nodeview-that-needs-context/843/2?u=rich) that
> node views should be treated as depending only on the node and its content, and no other external values
But I'm not sure I totally agree so have [asked for clarity](https://discuss.prosemirror.net/t/commands-inside-a-node-view/1440), and until then have implemented the idea discussed in that post.

Keep state up to date in node view

---

.eslintignore
.eslintrc.js
cypress/plugins/index.js
cypress/support/index.js
cypress/tests/unit/helpers.spec.ts
package.json
src/embed.ts
src/embeds/image/ImageEmbed.tsx
src/embeds/image/embed.tsx
src/embeds/image/types/Fields.ts
src/helpers.ts
src/index.ts
src/mount.ts
src/mounters/react/EmbedProvider.tsx
src/mounters/react/EmbedWrapper.tsx
src/mounters/react/mount.tsx
src/plugin.ts
src/prosemirror-example-setup.d.ts
src/types/Commands.ts
src/types/Consumer.ts
src/types/Embed.ts
src/types/Errors.ts
src/types/Fields.ts
src/types/Validator.ts
tsconfig.json
webpack.config.js
yarn.lock

Adds [Guardian-standard linting](https://www.npmjs.com/package/@guardian/eslint-config-typescript) to the project.
The code should work as before. Running `yarn` and then `yarn lint` in the project directory should pass.
There is no check to enforce this yet. This should come via a CI step w/ Github Actions.

Add linting

---

src/__tests__/embed.spec.ts
src/__tests__/helpers.ts
src/__tests__/mount.spec.ts
src/embed.ts
src/embeds/image/ImageEmbed.tsx
src/embeds/image/embed.tsx
src/index.ts
src/mount.ts
src/mounters/react/EmbedProvider.tsx
src/mounters/react/PropView.tsx
src/mounters/react/mount.tsx
src/nodeSpec.ts
src/nodeViews/CheckboxNodeView.ts
src/nodeViews/EmbedNodeView.ts
src/nodeViews/FieldNodeView.ts
src/nodeViews/RTENodeView.ts
src/nodeViews/helpers.ts
src/plugin.ts
src/pluginHelpers.ts
src/types/Consumer.ts
src/types/Embed.ts
src/types/Fields.ts
src/types/Validator.ts

This PR gets rid of the last vestiges of the previous sort of state management (a single, empty parent node, with lots of fields), in favour of the current sort of state management (one to many child nodes, which have content or fields).
We now display the current values of the fields, and their validation output, to show that everything's working as intended:
In doing the above, I've tried to 
- keep things as typesafe as possible. As a result, the validation and field values passed to the consumer code are now typesafe, with tests
- tried to name things sensibly, and comment the more complicated type wrangling that's needed for the above.
As a result, this diff is larger than I intended, mainly because there's lots of renaming – v. happy to pair on reviewing.
There's one bug, which is …

Remove Fields (flat state) in favour of Props (nested state), which are now called ... Fields

---

src/__tests__/helpers.ts
src/__tests__/mount.spec.ts
src/embedSpec.ts
src/renderers/react/EmbedProvider.tsx
src/renderers/react/createReactEmbedSpec.tsx
src/types/Consumer.ts

Removes the consumer function that's passed through `createEmbedSpec`. It's not used by `createEmbedSpec`, and is necessarily already in scope in the consumer context – so we don't need it as an argument. This simplifies the signature of `createEmbedSpec`.
This is a no-op – test should pass as before.

Refactor: remove the consumer argument from `createEmbedSpec`

---

cypress/tests/ImageElement.spec.ts
src/fieldViews/AttributeFieldView.ts
src/fieldViews/__tests__/AttributeFieldView.spec.ts
src/nodeSpec.ts

Fixes a problem with incorrect fields being passed to inheritors of `AttributeFieldView` – a straightforward problem papered over by the loose typing of the attributes in Prosemirror's `Node` type.
This also uncovered another problem, where `sameMarkup` was inappropriately being used to figure out whether we should accept updates. This isn't right – this check includes a [deep comparison of attributes](https://github.com/ProseMirror/prosemirror-model/blob/eef20c8c6dbf841b1d70859df5d59c21b5108a4f/src/node.js#L131), which aren't relevant for an identity check in this case, and will always produce an incorrect result once field attributes are updated.
The automated tests (unit and integration) should pass, and cover the cases discussed above.

Fix incorrect fields in AttributeFieldView passed on update

---

.eslintrc.js
cypress/tests/ImageElement.spec.ts
src/fieldViews/ProseMirrorFieldView.ts
src/fieldViews/RichTextFieldView.ts
src/fieldViews/TextFieldView.ts
src/fieldViews/helpers.ts
src/helpers.ts
src/pluginHelpers.ts

At the moment, for `ProsemirrorFieldView` instances, we swap nodes and transactions between inner and outer instances of Prosemirror editors transparently, but the editors have different schemas. This has worked by coincidence, so far.
I thought we'd need to translate between the inner and outer schemas on fieldView creation and update (outer -> inner) and when dispatching transactions on the outer editor (inner -> outer), but a discussion on the [Prosemirror forums](https://discuss.prosemirror.net/t/translating-nodes-and-transaction-steps-between-editors-with-different-schemas/3863) has clarified that this isn't necessary – the editor either doesn't seem to enforce the `topNode` specified in the schema, or assumes that the `topNode` is the node passed on initialisation.
So instead of …

Pass parent schema directly to children

---

README.md
package.json

At the moment, CI is hanging indefinitely when either linting or testing fails. IIUC, this is because (in `bash` at least) the & operator looks to have a higher associativity than &&, so if linting or tests fail, webpack serve is never called and we run wait-on in parallel, which will run indefinitely.
To test this, try running the following commands in your shell:
```bash
false && true && echo "This shouldn't appear" # no output
false && true & echo "This shouldn't appear" # echoes 'This shouldn't appear'
false && (true & echo "This shouldn't appear") # no output
```
Introduce e.g. a linting mistake and run `yarn ci`. Does the script fail fast with an exit code of `1`?

Correct CI script

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/helpers/test.ts

Previous to this PR, if the decorations in a rich text field changed but the node content remained the same, the field would not update its decorations.
This is a problem for an upcoming PR that displays user carets in a collaborative editing context – the carets are represented as decorations, and nested fields do not update the position of these carets until their documents change.
Because `Decoration`s and `DecorationSet`s are immutable, we can compare incoming decorations to the current decorations to see if they've changed, and flag. We can then ensure that if the document itself haven't changed but the decorations have, we dispatch a no-op transaction that forces the editor to rerender decorations, but leaves the document untouched.
I've added an action to our `testDecorationPlugin` …

Rerender decorations in rich text field when they change, even if the document hasn't

---

cypress/fixtures/example.json
src/elements/image/imageElement.tsx
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/helpers/plugin.ts
src/plugin/types/Element.ts

Creates a property in a RichTextField field declaration, `plugins: Plugin[]`, to allow element to pass plugins into fields directly. This replaces the current approach, where we just add an `exampleSetup` plugin arbitrarily.
This will eventually allow consumers to pass plugins to elements to govern RTE behaviour – e.g. at the Guardian we may do this to supply custom RTE menu bars in Composer, amongst other things.
I've added an exampleSetup plugin but ~turned menu bars off to show that the field is now governing plugin behaviour~ left menu bars in, as our integration tests rely on them 😅 
This is a no-op – the automated tests should pass.

Allow passing plugins into rich text editor fields

---

cypress/helpers/editor.ts
cypress/tests/ElementWrapper.spec.ts
cypress/tests/ImageElement.spec.ts
package.json
yarn.lock

#55 introduced an intermittent failure in our integration tests, caused by localStorage remaining populated between tests. This [shouldn't happen by default](https://docs.cypress.io/api/commands/clearlocalstorage).
This PR resets localStorage before each test manually.
It also bumps Cypress. This didn't fix the problem, but it's good to keep up to date.
The integration tests should pass, reliably.

Fix intermittent cypress failures

---

.gitignore
.metals/metals.lock.db
cypress/tests/ImageElement.spec.ts
src/editorial-source-components/CustomDropdown.tsx
src/elements/image/ImageElementForm.tsx
src/elements/image/imageElement.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/fieldViews/CheckboxFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/DropdownFieldView.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/fieldViews/helpers.ts
src/plugin/types/Element.ts

When creating elements at the moment we have to declare fields manually with object literals. This can mean that field declaration can be unnecessarily verbose and sometimes require type cast.
```ts 
mainImage: {
type: "custom",
defaultValue: { mediaId: undefined, mediaApiUri: undefined, assets: [] },
props: {
onSelectImage,
onCropImage,
},
} as CustomField<
{ mediaId?: string; mediaApiUri?: string; assets: string[] },
{
onSelectImage: (setSrc: SetMedia) => void;
onCropImage: (mediaId: string, setSrc: SetMedia) => void;
}
>
```
This PR introduces `creator` functions for each field type; this enables a more concise way of declaring fields:
```ts
mainImage: createCustomField<ImageField, ImageProps>(
{ mediaId: undefined, mediaApiUri: undefined, assets: [] },
{
onSelectImage,
onCropImage,
} …
```

add field creator functions to imageelements

---

.github/workflows/node-js.yml
.github/workflows/semantic-pr.yml
README.md
package.json

Adds [semantic-release](https://github.com/semantic-release/semantic-release) via a workflow and [github action](https://github.com/marketplace/actions/action-for-semantic-release). This means automated, semantically versioned releases with nicely formatted release histories – see [prosemirror-typerighter](https://github.com/guardian/prosemirror-typerighter/releases) for an example of a release history generated with this approach.
In order for semantic release to determine the correct version number, the project requires pull request names to be compliant with the [commitizen](https://github.com/commitizen-tools/commitizen) format: for example, `fix: a bug that was squashed` or `feat: an exciting new thing`.
This PR includes a github action that will validate the name of the PR in CI to …

chore: add semantic release

---

demo/index.ts
src/editorial-source-components/editor.ts

This PR makes some small changes to focus style, so that the wide focus ring only shows to users who are keyboard navigating, *not* selecting fields with the mouse.
This is accomplished by adding the Source `FocusStyleManager`, and running `FocusStyleManager.onlyShowFocusOnTabs();`. this only needs to be done once per application - and may also need to be done in applications using our Source-styled Elements.
Run `yarn start` locally and use the `Element`.

feat: Only show focus when the user is keyboard navigating, not clicking

---

src/renderers/react/ElementWrapper.tsx

This styles the sidebar in the element to be an appropriate size in Firefox.
Run `yarn start` and visit https://prosemirror-elements.local.dev-gutools.co.uk/

fix: Fix Firefox styling problem

---

src/elements/demo-image/DemoImageElement.tsx
src/plugin/helpers/validation.spec.ts
src/plugin/helpers/validation.ts

_co-authored-with: @dskamiotis, @rhystmills_  
Adds a validation helper function that allows the user to compose validators against fields. This should make common validation tasks easier to express.
- The unit tests should pass. The new unit tests should adequately demonstrate the helper's behaviour.
- The validation applied to the demo element should work as expected – take a look at the `DemoImageElement` declaration, and compare it to the runtime behaviour.
We have an easier time expressing validation with new elements.

feat: add validation helpers

---

src/editorial-source-components/Error.tsx
src/editorial-source-components/Field.tsx
src/editorial-source-components/InputGroup.tsx
src/editorial-source-components/InputHeading.tsx
src/editorial-source-components/editor.ts
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/plugin/fieldViews/helpers.ts
src/plugin/helpers/validation.spec.ts
src/plugin/helpers/validation.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/FieldView.tsx

Gives us some common components to express error messages in the UI.
I haven't altered our custom components, as I'm aware that there may be changes needed downstream, but hopefully the `Field` component contains a template to work from.
Before:
After (note more readable labels, validation message and highlighting, consistent margins):
Do the changes look OK? Do the components look reusable for other elements?

feat: spruce validation UI

---

src/plugin/fieldViews/AttributeFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts

A quick PR to make the type parameter names for FieldViews more consistent (`Fields`|`CustomFieldValue`|`Value` -> `Value`).
Did I catch 'em all?

chore: Consistent type parameters for FieldViews

---

cypress/tests/ImageElement.spec.ts
demo/helpers.ts
src/editorial-source-components/Field.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/plugin/fieldViews/AttributeFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/DropdownFieldView.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/AttributeFieldView.spec.ts
src/plugin/fieldViews/helpers.ts
src/plugin/helpers/plugin.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/FieldView.tsx

_co-authored-by: @dskamiotis_ 
Adds an function to allow us to programmatically update fields to the `FieldViewSpec` type:
```ts
<button
data-cy={UpdateAltTextButtonId}
onClick={() => fieldViewSpecs.altText.update("Default alt text")}
>
```
The function is typesafe, and should only allow us to pass values that match the type handled by the field.
See `DemoImageElement.tsx`, where it's used in the example above, and to programmatically update the `altText` and `caption` fields when we receive a new image.
- The new integration test should pass, and you should be convinced it's testing a programmatic update.
- Add a new image to the demo image element. Does that operation also update the altText and caption fields with the description of that image?
In order to keep our types as simple as …

feat: Add API to programmatically update fields

---

docs/vision.md

This PR adds an initial version of our ProseMirror-Elements vision document. It provides a clear set of challenges, ambition and guiding principals which can be used to help orient the direction of the project.
When key decisions need to be made, we can refer to this document to see how the different options compare to our guiding principals. It should also provide a clear definition of the problem we are aiming to solve and why.

docs: Adds vision document

---

src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/pullquote/PullquoteSpec.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/elementSpec.ts
src/plugin/helpers/test.ts
src/plugin/plugin.ts
src/renderers/react/createReactElementSpec.tsx

Removes our element-level defaults. We ... didn't really use them, except (incorrectly) on initialisation! They were a hangover from a previous design, and there weren't any tests to verify they had an effect.
This fixes an incidental bug where validation errors were not appearing when nodes were initialised on doc serialisation (card [here](https://trello.com/c/ygmh8P87/718-resolve-validation-issue)).
- The automated tests should pass, and they should satisfy you that defaults are respected.
- Add content to a required field w/ the DemoImageElement, and refresh the page. The validation message should not appear.

fix: Remove element defaults

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
demo/index.ts
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/nodeSpec.ts

_> co-authored-by: @rhystmills_ 
Expands the options for rich text options to accommodate a modified `NodeSpec`. This can be useful when e.g. restricting marks, or specifying different kinds of content.
The `createRichTextField` field creator signature has been modified to allow these options to be passed.
We think there's room for a new field creator, alongside `createDefaultRichTextField`, to create a field that does not include paragraphs – perhaps `createFlatRichTextField`. This would reduce some repetition when declaring fields – for example, all of our captions across different elements are likely to use these defaults.
This would also need to include a binding for the `enter` key that inserts a hard_break (as with the multiline text input)  – but that can be added in a separate PR. …

feat: Expand rich text options to accommodate a modified NodeSpec 

---

cypress/tests/ImageElement.spec.ts
demo/index.ts
src/elements/demo-image/DemoImageElement.tsx
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts

Adds a `createFlatRichTextField` field creator. (It's not a great name, eh. Can we think of a better one? `createNoParaRichTextField`?)
It creates a rich text field that doesn't use paragraphs – instead, it produces flat text, with `br` tags for line breaks.
To do this, the field adds two pieces of configuration –
- adds a keymapping from `Enter` that adds a `br` tag
- specifies the content for the node to be `(text|hard_break)*`
The user is free to add plugins or alter other parts of the `NodeSpec` themselves.
This effectively duplicates the testable functionality of #75 in a helper function. I've added a test to check that the enter key works.
Try the field out in the demo element. Does it work as expected? Does the output match what we describe above?

feat: Add `createFlatRichTextField` field creator

---

src/plugin/__tests__/element.spec.ts
src/plugin/element.ts
src/plugin/elementSpec.ts
src/plugin/helpers/element.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/createReactElementSpec.tsx

_co-authored-by: @rhystmills_ 
Adds the ability to add options transformer functions to an element spec. These transformer functions let consumers transform data between an external representation of element data, and the `prosemirror-elements` representation.
As an example, at the Guardian, flexible-content expresses our elements as 
```ts
{
elementType: string,
fields: { ... element fields },
assets: Asset[]
}
```
Additionally, some elements require additional, static field values, e.g. `isMandatory`, which aren't present in the element fields.
By allowing the consumer to supply a transformer function on a per-element basis, and applying them when `getElementDataFromNode` and `getNodeFromElementData` are called, we can ensure that we keep the internal and external models are kept …

feat: Add transformer functions when getting element data from nodes, and vice versa

---

src/plugin/helpers/prosemirror.ts
src/plugin/nodeSpec.ts
src/plugin/plugin.ts

This PR fixes a small issue with the element wrapper arrows not updating correctly. This can mean it's possible for the element to become stuck in a single position. 
The fix works by building on an existing solution which applies an invisible decoration to all elements, ensuring any updates are caught and process. This decoration was only previously applied to the image element as the decoration was looking for an element with a certain name.
There may be nice and more performant ways of ensuring these arrows update, but this will resolve the issue for now.
Using this branch, do the wrapper arrows function correctly?
before: 
after:

fix: Fixes element wrapper arrows not updating correctly

---

src/plugin/__tests__/element.spec.ts
src/plugin/helpers/element.ts

Removes some typesafety for `getNodeFromElementData` in favour of a runtime check. In our CMS, we often have operations that iterate through a series of elements to conditionally produce nodes. Not all of those elements will be managed by this plugin. As a result, a better API is to conditionally return a node _if_ this node is handled by prosemirror-elements.
For example, this code, if strictly typed, will not be possible: 
```ts
const elements = documentElements; // Some of these aren't handled by prosemirror-elements
const nodes = elements.map(getNodeFromElement) // as a result, this will not typecheck
```
We'd have to write something like this, instead:
```ts
const elements = documentElements; // Some of these aren't handled by prosemirror-elements
const nodes = elements.map(element …
```

feat: Remove typesafety for getNodeFromElementData

---

src/plugin/__tests__/elementSpec.spec.ts
src/plugin/element.ts
src/plugin/nodeSpec.ts

At the moment, we hardcode our group name into the element nodeSpec. This doesn't work in our CMS, which expects an 'element' group. Other consumers may expect other groups – so, this PR allows the consumer to specify, defaulting to 'block', as it's already present in the default schema and will make it easy to experiment with this library.
- The new automated test should pass.
- You should be able to see the new groupName in the schema.

feat: Add custom groupName to elements

---

src/elements/__tests__/createGuElementSpec.spec.tsx
src/elements/code/CodeElementSpec.tsx
src/elements/createGuElementSpec.ts
src/elements/helpers/index.ts

Adds a new function, `createGuElement`, to take care of boilerplate when creating Guardian-specific Elements. This function makes two assumptions:
- you want to use React to render the element, with the standard `ElementWrapper`
- you need to transform the flat fields generated by prosemirror-elements to fit the [`flexible-model` format.](https://github.com/guardian/flexible-model/blob/main/src/main/thrift/content.thrift)
Eventually this function is intended to live in a specific gu-elements package, alongside the Guardian-specific elements that currently live alongside it in the `elements` folder.
The automated test should pass. It roundtrips element data, expressed in the flexible-model format, into and out of a prosemirror node.
This PR (incorrectly!) assumes that the assets will …

feat: Add gu element creator

---

src/plugin/__tests__/element.spec.ts
src/plugin/helpers/element.ts

At the moment, `getElementDataFromNode` always expects to be passed a node representing an element. But how do we know this before we pass one?
This PR alters its signature and implementation to accept any node, and return `undefined` if it receives something it doesn't recognise.
This makes it easy to iterate through a document in consumer code, passing nodes blindly into `getElementDataFromNode` for transformation, and handling them in some other way if we receive `undefined`.
The automated tests should pass, and adequately test for this condition.

feat: Handle passing non-element nodes to getElementDataFromNode

---

cypress/helpers/editor.ts
src/elements/createGuElementSpec.ts
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/fieldViews/CheckboxFieldView.ts
src/plugin/fieldViews/__tests__/AttributeFieldView.spec.ts
src/plugin/plugin.ts

This PR un-nests the checkbox field values, which should make them a little easier to work.
Before:
`CheckboxValue = { value: boolean };`
After
`CheckboxValue = boolean;`
This should be a no-op in terms of functionality but make checkbox fields easier to work with.

refactor: Un-nests checkbox field values

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/plugin/nodeSpec.ts

This PR restrict all marks in text fields to prevent them from being added by other means i.e. copy and paste.
Trying copying some text from an RTE field with marks into a text field. 
There is currently no Cypress test that checks this path, but I  have added some shortcut tests for good measure.
Text fields never contain marks.

fix: Restrict marks in text elements

---

cypress/helpers/editor.ts
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/nodeSpec.ts

_co-authored-by: @rhystmills_
Removes custom tags and classes from serialised elements, in favour of attributes prefixed by `pm-elements`.
Using custom tags isn't recommend by the [W3C spec](https://html.spec.whatwg.org/multipage/dom.html#elements), and has caused problems where element names have coincided with actual element names (e.g. `code`), causing odd behaviour. We could namespace element tags to solve the latter, but making them `divs` also solves the former.
The tests have been modified to reflect the new HTML output, but this is a no-op – everything should work as before.

feat: Remove custom tags and classes

---

src/elements/__tests__/createGuElementSpec.spec.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/elementSpec.ts
src/plugin/helpers/element.ts
src/plugin/helpers/prosemirror.ts
src/plugin/helpers/test.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx

Adds the validation results to the output of `getElementDataFromNode`. This makes it easy for consumers to get hold of results when they're processing the output of the plugin.
The new automated test should pass, and it should be clear what it's doing.
I've changed the output of the `Validator` function in this PR from `null` to `undefined` – we don't use `null` anywhere else in this library, and I'm not aware of a good reason to use it over `undefined` in this instance, but I'd be interested if there was a rationale!

feat: Add validation results to `getElementDataFromNode`

---

src/elements/__tests__/createGuElementSpec.spec.tsx
src/elements/code/CodeElementForm.tsx
src/elements/code/CodeElementSpec.tsx
src/elements/createGuElementSpec.ts

Alter the field names of code element to correspond with flexible-content. In doing this, we also need to strip `isMandatory` from elements that don't explicitly need it – `isMandatory` is ... not required.
- The automated tests should pass.
- The fields for the Code element should be `html` and `language` in the prosemirror dev tools.
Tested locally in Composer via `yarn link`.

fix: Alter fields of code element to correspond with flexible-content

---

src/renderers/react/ElementWrapper.tsx

Changes a `first-child` selector to a `first-of-type` selector to avoid red in produced by Emotion, and adds `type='button'` attributes to our buttons to prevent them from submitting forms unintentionally.
The changes above should be reflected in the markup.

fix: Minor changes to HTML

---

src/renderers/react/ElementWrapper.tsx

This adds an `aria-label` attribute to our move and delete element buttons.
The buttons do not contain text so currently their purpose is not clear when using a screen reader.
Run `yarn start` and test via a screenreader, e.g. VoiceOver on Mac.

fix: Add aria-labels to move and delete element buttons

---

demo/style.css
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts

At the moment, in the demo page, we inherit lots of styles from the Prosemirror css directly, imported from the Prosemirror website. This PR moves many these styles in-house, removing the dependency on external stylesheets and making it explicit what assumptions our demo page is making re: instance styling.
It also adds classes to the Prosemirror DOM nodes created by both the Text and RichText FieldViews. This allows consumers to target them directly.
- Is the demo page still styled correctly?
- Do classes appear on the root nodes of nested Prosemirror instances according to their FieldView? You should see e.g.

feat: Add classes to nested Prosemirror instances for consumer styling

---

src/editorial-source-components/CustomDropdown.tsx
src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/pullquote/PullquoteSpec.tsx
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/DropdownFieldView.ts
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

After a discussion of how to handle undefined values in dropdown, this PR attempts to save some of the little tweaks that were made to enable it. #96 and #99 will be closed due to a concern about adding too much additional complexity to support non-serializable types i.e. undefined.
This change should be a no-op and all tests should pass as before.
It's easier to work with custom dropdowns.

refactor: Refactor dropdown types

---

cypress/helpers/editor.ts
demo/helpers.ts
demo/index.ts
package.json
src/editorial-source-components/FieldWrapper.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/image/ImageElement.tsx
src/elements/image/ImageElementForm.tsx
src/index.ts
yarn.lock

co-authored with @SHession 
This PR adds an Image Element replicating the existing Embed element in Composer. However this element includes more functionality and buttons to access the Grid for images.
This PR also:
- adds a `CustomDropDown` which renders a modified Source Dropdown (allowing for clearer displayed text and improved - arrow button).
- includes the use of `createTextField` as a text area allowing for multi line 
- adds a createTextField with multiline capabilities set with a default of 4 lines.
- Field labels included as prop from Component
- Accesses Grid instantly when image element button selected
- Buttons to re crop/change selected image and copy caption to alt text field
- Logic to deal with Assets from Grid defaulting to those of 1000px width and the next largest as a …

feat: Create Image Element

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
demo/index.ts
demo/types.ts
src/plugin/nodeSpec.ts

#89 was incomplete – it didn't remove custom tags from the deserialisation step (`getAttrs`) in the nodeSpec declaration for rich text elements.
As a result, we were seeing odd results when deserialising from HTML:
This PR makes that change, adding a test beforehand to verify that this behaviour is fixed, as it was previously a blind spot.
Our `getAttrs` function was still using old code that expected a div with a custom element tag (e.g. `<element-image-element-caption>`, rather than `<div pme-field-name="imageElement_caption">`.
So, we serialised the element correctly, but when Prosemirror attempted to deserialise the element (e.g. on a page refresh, as we store the document as html in localStorage), Prosemirror didn't understand the shape of the rich text data – it was expecting …

fix: Remove custom tags for rich text elements

---

src/plugin/__tests__/element.spec.ts
src/plugin/element.ts
src/plugin/helpers/element.ts
src/plugin/helpers/test.ts
src/plugin/types/Element.ts

This PR changes how the validation logic is surfaced to the consumer. With this PR it is no longer returned from`getElementFromNode` but instead a function is provided called `elementDataValidator` which can be used to validate element values.
I have added some additional unit tests to ensure the functionality is working correctly, but should be a no-op for the demo.
Consumers have an easy way of validating element values, whilst validation logic is nicely encapsulated within the element spec.

feat: refactor validation api

---

cypress/tests/ElementWrapper.spec.ts
src/editorial-source-components/SvgBin.tsx
src/renderers/react/ElementWrapper.tsx

Elements in Composer ([flexible-content](https://github.com/guardian/flexible-content)) currently require two clicks to close, but the implementation is not working very well. 
In order to be consistent with this existing behaviour (especially during migration where some, but not all, elements may be migrated), this PR adds 'click to confirm close' behaviour to our ProseMirror Elements. However, we've tidied the implementation with a new hover tooltip. As before, there is only a limited timeframe in which a user can confirm the close, after which a timeout occurs, and the button returns to its initial state.
**Once all elements are migrated to ProseMirror, we can revisit whether we want this behaviour at all.**
(N.B - due to a lack of bin icon in Source, we've borrowed one from the …

feat: Click to confirm element close

---

src/editorial-source-components/FieldWrapper.tsx
src/elements/code/CodeElementForm.tsx
src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/embed/EmbedForm.tsx
src/elements/image/ImageElementForm.tsx
src/elements/pullquote/PullquoteForm.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/elementSpec.ts
src/plugin/helpers/element.ts
src/plugin/helpers/validation.spec.ts
src/plugin/helpers/validation.ts
src/plugin/types/Consumer.ts
src/plugin/types/Errors.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/customFieldViewComponents/CustomCheckboxView.tsx
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

This PR adds a `ValidationError` type which provides more error information than previously by including an additional `message` property and using the existing string as the `error` property. It also adds a `FieldValidationErrors` type for convenience and readability.
```
export type ValidationError = {
error: string;
message: string;
};
export type FieldValidationErrors = Record<string, ValidationError[]>
```
This should be a no-op from a user perspective but provide consumers and the view with more information about validation problems.
We have enough data to display clear validation messages to consumers.

feat: Adds ValidationError type into validator

---

cypress/helpers/editor.ts
demo/index.ts
src/editorial-source-components/Editor.ts
src/editorial-source-components/FieldWrapper.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/element.ts
src/plugin/elementSpec.ts
src/plugin/nodeSpec.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/FieldView.tsx

This PR removes the `hasErrors` state and function as it has now been usurped by the validator function.
This should be a no-op but make the code cleaner by removing redundant code.
The code is easier to work with, in accordance with our vision document.
Is there any chance we may need this?

refactor: Removes the hasErrors function and state as it's no longer needed

---

src/elements/image/ImageElement.tsx
src/elements/image/ImageElementForm.tsx
src/elements/image/imageElementValidation.tsx
src/plugin/helpers/validation.ts

This replicates the image size warning for the Image element, which is present in the existing element in Composer. This warning occurs when the largest asset available has at least one dimension smaller than 460px.
There's quite a bit of code here to allow us remain type-safe while validating the image fields. Is this valuable enough to justify not simply asserting the type using `as`?
Run `yarn start` locally and try using a crop with a dimension smaller than 460px.
| Too Small | Correct Size |
| --- | --- |
| ![2021-09-09 09 19 42](https://user-images.githubusercontent.com/34686302/132650222-fe422c21-d586-4fc3-b8f9-2374cae85ada.gif) | ![2021-09-09 09 20 06](https://user-images.githubusercontent.com/34686302/132650201-281b71aa-b357-4015-8a87-5bb58db1fafd.gif) |

feat: Image size warning

---

src/editorial-source-components/Editor.ts
src/editorial-source-components/FieldWrapper.tsx
src/renderers/react/FieldView.tsx

This PR fixes a regression introduced by #111, which removed the red border from field when an error is found.
Add an element with validation, if the validation fails, does the field highlight red?

fix: Fixes validation error border on fields

---

src/plugin/helpers/validation.ts

This PR makes the validators more tolerant of different types and changes the paradigm to not throw exceptions of the types don't match what's expected. 
This should make the validators easier to work with in Composer where the shape of elements may differ slightly from PME spec.
This should be a no-op functionally but make the validators easier to work with in Composer.
Validators accept shapes which don't entirely match but still produce useful errors.

fix: Prevents validators from throwing errors and allow undefined

---

src/editorial-source-components/Button.tsx
src/elements/image/ImageElementForm.tsx

co-authored @rhystmills 
We are currently using Source button for the `copy from caption` and `re crop image` on the image element.
In order to keep the styling in line with the rest of Composer we would like the font for the text to be Agate Sans.
This PR aims to amend the default font for the source button to Agate Sans.
Run `yarn start` from the repository root and try closing an element.
Also using dev tools; inspect the font source (as screenshots below)
In order to implement this the following additions were made to this feature:
* New Button component created in its own file
* The button component is based off of Source button
* Additional styling added through props to override the default font
* Re factor the default props for Source button to allow for our custom button
| …

feat: Button font update for image elelemt

---

src/elements/pullquote/PullquoteForm.tsx
src/elements/pullquote/PullquoteSpec.tsx

Co-authored by @dskamiotis 
Update's the Pullquote element's property names to match those expected by Composer.
This should be a no-op in Prosemirror-Elements, but will allow the element to function properly in Composer.
Run `yarn start` from the repository root.

fix: Update property names to match interface expected by Composer

---

src/elements/pullquote/PullquoteForm.tsx
src/elements/pullquote/PullquoteSpec.tsx

Repeating as first change did not give semantic commit message.
Co-authored by @dskamiotis 
Update's the Pullquote element's property names to match those expected by Composer.
This should be a no-op in Prosemirror-Elements, but will allow the element to function properly in Composer.
Run `yarn start` from the repository root.

fix: Update property names to match interface expected by Composer (again)

---

src/editorial-source-components/CustomCheckbox.tsx
src/editorial-source-components/CustomDropdown.tsx
src/editorial-source-components/Error.tsx
src/editorial-source-components/InputHeading.tsx
src/editorial-source-components/Label.tsx

Allows error messages to wrap beneath labels when they exceed a single line.
Before:
After:
Have a play with our elements. Do our error messages behave as expected? Is everything else as it should be?
It'd be nice to specify elements programmatically (`${label} {` rather than `label {` in InputHeading), but we can't do that without adding a babel plugin. That's probably another PR.

fix: Allow error messages to wrap beneath labels 

---

src/elements/code/CodeElementSpec.tsx
src/elements/createGuElementSpec.ts
src/elements/demo-image/DemoImageElement.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/image/ImageElement.tsx
src/elements/image/imageElementValidation.tsx
src/elements/pullquote/PullquoteSpec.tsx
src/plugin/elementSpec.ts
src/plugin/fieldViews/CheckboxFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/DropdownFieldView.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/helpers/validation.ts
src/renderers/react/createReactElementSpec.tsx

This PR changes the field description API to allow the possibility of colocating the validation with the field. This should make the API easier to work with in line with our vision document goals.
Before:
```javascript
export const pullquoteFields = {
html: createTextField({ isMultiline: true, rows: 4 }),
};
export const pullquoteElement = createReactElementSpec(
pullquoteFields,
(_, errors, __, fields) => {
return <PullquoteElementForm errors={errors} fields={fields} />;
},
createValidator({ pullquote: [htmlRequired()] })
);
```
After: 
```javascript 
export const pullquoteFields = {
html: createTextField({
multilineOptions: { isMultiline: true, rows: 4 },
validators: [htmlRequired()],
})
};
export const pullquoteElement = createReactElementSpec(
pullquoteFields,
(_, errors, __, fields) …
```

feat: Move validation into field descriptions

---

src/elements/embed/EmbedSpec.tsx
src/elements/image/ImageElement.tsx
src/elements/pullquote/PullquoteSpec.tsx

Use `createGuElementSpec` for all flexible-model elements. Previously, this was limited to just code – now we use that method for the lot, ensuring that our data is in the correct shape for flexible-conte.
Use this library in flexible-content. Does it work as expected?

fix: Use createGuElementSpec for flexible-model elements

---

src/editorial-source-components/FieldWrapper.tsx
src/editorial-source-components/InputHeading.tsx
src/editorial-source-components/Label.tsx
src/elements/image/ImageElementForm.tsx

A few layout changes for the image element:
1) Moves the 'copy from altText' button inline with its label. 
To do this, I've changed the `label` prop to accept a`ReactNode`,  allowing us to pass arbitrary content in as a label. Because strings are `ReactNode`s, we can pass strings as usual.
2) Adjusts the photographer columns, which were not full width.
3) Changes buttons from 'primary' to 'secondary' to reflect [docs](https://theguardian.design/2a1e5182b/p/435225-button/b/86f344): 'use for actions that need to be clear, but aren’t the primary focus of a page.'
There are two more things that I think are worth changing:
- the 'weighting' field is not inline
- the spacing between 'alt text' and 'photographer' fields is not consistent (because flex/grid  elements [do not permit margin …

fix: Image element layout changes

---

src/elements/pullquote/PullquoteSpec.tsx

Updates the copy for the empty pullquote element error, from: "Html is required" to "Pullquote cannot be empty".

feat: Update copy for empty pullquote element error

---

src/elements/pullquote/PullquoteSpec.tsx

Opened because previous PR's commit didn't include the semantic release keyword.
Updates the copy for the empty pullquote element error, from: "Html is required" to "Pullquote cannot be empty".

feat: Update copy for empty pullquote element

---

src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/image/ImageElement.tsx
src/elements/pullquote/PullquoteSpec.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/fieldViews/helpers.ts
src/plugin/helpers/element.ts
src/plugin/helpers/types.ts
src/plugin/types/Element.ts

_co-authored-by: @rhystmills_ 
Adds an `absentOnEmpty` option for text fields. Setting this option to `true` will not set a key-value pair on data returned from `getElementDataFromNode` if the field is empty.
Empty here means no text content, so a rich text field that serialises to e.g. `<p></p>` will be considered empty.
This change is required to better match the way absent data is modelled in Composer, the Guardian's content management system.
The automated tests should pass, and test for the presence and absence of fields that use this flag, as well as the typesafety of the resulting data.
The surface area of this work is slightly larger than might be expected for two reasons:
- it was better to refactor the options object of the text fields to incorporate `absentOnEmpty`, which …

feat: add `absentOnEmpty` option for text fields

---

.github/PULL_REQUEST_TEMPLATE.md
src/renderers/react/ElementWrapper.tsx

This PR adds a PR template which extends our accessibility checklist to match the [Editorial Tools Accessibility guidelines](https://github.com/guardian/accessibility/blob/main/editorial-tools-guidelines.md).
These will look like:
<s>[No content flashes more than three times in any one second period](https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html)</s>

docs: Extended accessibility checklist

---

src/editorial-source-components/CustomCheckbox.tsx
src/editorial-source-components/CustomDropdown.tsx
src/editorial-source-components/FieldWrapper.tsx
src/editorial-source-components/InputGroup.tsx
src/editorial-source-components/InputHeading.tsx
src/editorial-source-components/Label.tsx
src/editorial-source-components/VerticalFieldLayout.tsx
src/elements/code/CodeElementForm.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/embed/EmbedForm.tsx
src/elements/image/ImageElementForm.tsx
src/elements/pullquote/PullquoteForm.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

Adds a layout component to take care of spacing our fields vertically.
This was previously done with margins, which mostly worked – but because `flex` doesn't permit [margin-collapse](https://css-tricks.com/the-rules-of-margin-collapse/), we had a problem with fields meeting flex containers.
A single component in charge of vertical spacing makes easier to make global adjustments to layout.
Here's a fun spot-the-difference that I've ruined for everyone! 
Before:
After: 
Besides the small change in the before/after, this should be a no-op. Do all the elements look as they should?

fix: Add FieldVerticalLayout component and remove margins from inputs/labels

---

src/plugin/__tests__/elementSpec.spec.ts
src/plugin/elementSpec.ts
src/plugin/helpers/validation.spec.ts
src/plugin/helpers/validation.ts

Building on the work from #120, this PR changes the validator type to accept a partial representation of the element data. This should allow us validate elements that are missing data. This will be helpfully when validating elements in Composer which currently model empty fields as undefined.
This should be a no-op for the demo and I have added an additional unit test to check a partial element.
We are able to determine if elements are valid or not with a partial set of data.

feat: Changes validators to accept a partial representation of the element

---

src/plugin/__tests__/element.spec.ts
src/plugin/helpers/element.ts

Avoids parsing plain text fields as HTML, which has the side effect of [encoding HTML entities](https://developer.mozilla.org/en-US/docs/Glossary/Entity). This was showing up in pullquote and code elements.
This might be considered a nice side effect in some cases, but probably shouldn't be a default. We could consider adding this as a parameter if needed.
- The new automated tests should pass, and convince you that they test for the correct behaviour.

fix: Do not html-encode plain text

---

cypress/tests/ImageElement.spec.ts
src/plugin/__tests__/element.spec.ts
src/plugin/nodeSpec.ts

#127 did not address a problem with HTML chars on ingress via `getNodeFromElementData` – we were using `innerHTML` to parse text.
This PR makes text nodes a special case on ingress (as #127 does on egress), manually creating text nodes rather than parsing as HTML.
As well as being more correct, this should also be quicker!
I don't _think_ there's a way to access this behaviour via the demo UI.  But the automated tests should pass, and you should be convinced they test for the problem. I wrote the unit test in a failing state, and then fixed. The amended integration test is also good confirmation.

fix: Address problem w/ html tags in plain text field

---

demo/index.ts
src/elements/image/ImageElement.tsx

This PR allows a consumer of the image element to provide a custom set of plugins via a plugin creator function. This should mean we can use Composer's custom menu bar within the caption field.
This should be a no-op as the demo instance will use the same plugins.
We are able to use the Composer menu bar with the image element.

feat: Changes ImageElement to accept a plugin creator prop

---

docs/decision-records/000-element-fields-model.md
docs/decision-records/001-transformers.md

Adds an ADR for the element transformers work. After chatting with the team, this is arguably a bit extra – but it's done now!
Have a read of the doc. Is it useful? Anything to change?

docs: Add ADR for element transformers

---

src/editorial-source-components/Description.tsx
src/editorial-source-components/FieldWrapper.tsx
src/editorial-source-components/InputHeading.tsx
src/elements/image/ImageElement.tsx
src/elements/image/ImageElementForm.tsx
src/elements/image/__tests__/imageElementDataTransformer.spec.ts
src/elements/image/imageElementDataTransformer.ts
src/elements/image/imageElementValidation.ts
src/elements/transformer/__tests__/transform.spec.ts

This PR makes various tweaks to the image element, in order to more closely align it to the existing element.
These changes are:
1. Handling the undefined value of the "weighting" dropdown
2. Displaying a character count for the "caption" field
3. Handling assets with a width and heigh of string 
4. Updates button to use "Guardian Agate Sans"
The tests should pass and the behaviour described above should work correctly in the demo and composer.
Our PME image element more closely matches the existing composer version.

feat: Image element tweaks

---

src/editorial-source-components/FieldWrapper.tsx
src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/image/ImageElement.tsx
src/elements/pullquote/PullquoteSpec.tsx
src/plugin/types/Consumer.ts
src/renderers/react/ElementProvider.tsx

- Reorders our consumer arguments in order of most common usage.
- Removes the requirement for an error object on FieldWrapper, avoiding boilerplate for fields that do not have validation.
The refactored code should look cleaner, with fewer missed arguments. (There's also an argument for an options object for our consumer arguments, but we can tackle that another time!)
I haven't removed unused error objects in existing fields, because it's a bit risky – I think there's a strong case to colocate the errors on the existing `Field` objects, preventing these sorts of problems in the first place.

feat: minor refactors re: feedback

---

src/plugin/elementSpec.ts
src/plugin/helpers/validation.spec.ts
src/plugin/helpers/validation.ts

This PR aims to fix a small bug which was causing validation errors to be lost. This would happen if a field had multiple validators. These validators could then overwrite previous errors. 
This PR fixes the bug and adds additional unit tests to ensure there are no further issues.
NB: I think the API for the validator needs to be reconsidered. The format of errors we output is slightly confusing, occasionally outputting undefined or fields with an empty error array. In addition, the error and field errors don't currently play nicely. I think these are changes which can be handled under a separate PR.
Are the unit tests thorough enough to give us confidence the change is working? Does the image element source character limit display as expected? 
Field validation errors are surfaced …

fix: Fix validation bug

---

src/elements/image/ImageElement.tsx
src/elements/image/ImageElementForm.tsx
src/elements/image/imageElementValidation.ts
src/plugin/__tests__/element.spec.ts
src/plugin/elementSpec.ts
src/plugin/helpers/__tests__/validation.spec.ts
src/plugin/helpers/validation.ts
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

This PR builds on the work of #133 and implements a few missing bits of functionality for the image element. These features currently exist in the Composer version.
These are: 
1. Preserving field values if a new crop is for the same image
2. Restricting image role values to "thumbnail" if the crop is too small
3. Adding an error level to validation errors to be used in pre-publish checks
For the image element:
1. Changing an image crop should preserve the field values if the image is the same, and replace them if it's different
2. Choosing a small crop should restrict the role value to "thumbnail"
3. Validation errors should appear as normal but have an associated level
Our PME image element closely matches the Composer version.

feat: Image element tweaks II

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/elements/demo-image/DemoImageElement.tsx
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/helpers/__tests__/placeholder.spec.ts
src/plugin/helpers/fieldView.ts
src/plugin/helpers/placeholder.ts
src/plugin/helpers/test.ts
src/plugin/plugin.ts

Adds a placeholder option for text and rich text fields.
The placeholder option can be a string, which PME will use to populate a span element of its own styling – or a function that returns a span, which the user can style and add content to themselves.
Behold!
NB: This does not address placeholders for accessibility purposes (e.g. `aria-placeholder`). We can address this is a separate PR.
- Both unit and integration tests should pass, and convince you that the placeholders are working as expected.
- Have a play locally – does everything look OK?

feat: Add placeholder option for text and rich text fields

---

src/elements/image/ImageElement.tsx
src/elements/pullquote/PullquoteSpec.tsx

This PR uses the work from #138 to add placeholder text to the fields in the existing elements.
Create an image and pullquote element in the demo environment. Does placeholder text appear when there is no content?
Does the placeholder look as it should?
Image:
Pullquote:
There are placeholder features not yet implemented as mentioned in #138

fix: Adds placeholder text to existing elements

---

src/plugin/helpers/placeholder.ts

This PR fixes a placeholder text overflow issue, causing placeholder text to stretch beyond its bounds. This is achieved through some small styling tweaks.
Load the demo page, does the placeholder test reasonably stay within its bounds?
Before:
After (is it me or is this an optical illusion?):

fix: Fixes the placeholder text overflow UI bug

---

cypress/tests/ImageElement.spec.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts

Fixes an odd issue where decorations passed to child editors might appear in the wrong place, or not appear at all, in certain situations.
This was caused by the code responsible for applying the decorations reading from class properties that had yet to be updated. A cautionary tale about mutating and reading from local state!
The added integration tests should pass. Take a look – do they clearly describe what they're testing?
To test manually, see the gifs below – adding and removing text adjacent to decorations, either in the same field or in a subsequent field, had odd results, as they were working with a stale offset and node.
| --- | --- |
| ![2021-10-05 09 31 28](https://user-images.githubusercontent.com/7767575/135988703-eabd36fc-0c21-4fb7-8934-3c02bc329933.gif) …

fix: Fix decoration jitter

---

README.md

A simple PR to add instructions for running and testing prosemirror-elements locally.
This is especially useful for testing a local branch (pre `push`ing) within `flexible-content` and viewing your element in composer local `https://composer.local.dev-gutools.co.uk/`.
note: we may need want to remove the yarn link section of the readme

docs: add yalc instructions to readme

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/elements/code/CodeElementSpec.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/image/ImageElement.tsx
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts

Adds an `isResizeable` property to text and richtext fields, to allow both sorts to be resizeable by users in the usual way. This PR also applies this to our image alt text, to reflect the current behaviour of the old image element:
There's one decision I've made here that's worth mentioning – when an input is resizeable, we default its initial size to the number of rows specified in the `rows` property. I thought this made a sort of heuristic sense, as whenever we make something resizeable, we're likely expecting lots of content in a limited space – but others may disagree! We can use `maxRows` to ensure that users can't expand inputs indefinitely if required.
Incidentally, I was dusting off the HTML5 drag and drop API docs before I found out this was possible with CSS – phew! 😅 
- Drag …

feat: Add resizeable property to text and richText fields, and apply to image altText

---

demo/index.ts
src/elements/helpers/transform.ts
src/elements/rich-link/RichlinkForm.tsx
src/elements/rich-link/RichlinkSpec.tsx
src/index.ts
src/renderers/react/ElementWrapper.tsx

This PR adds a `rich-link` element replicating the existing element in Composer PROD. 
This PR also:
- adds "rich-link" as a string as a defaultElementTransform 
- creates demo rich-link element for sandbox with button, generating example text for link to article
- add `min-height` styling to ElementWrapper to ensure grey body gives enough space to arrow/controls to be shown clearly
Run `yarn start` locally and add an rich-link element.
To test this with `flexible-content` locally, I used [`yalc`](https://github.com/wclr/yalc). If you want to do the same: 
1. Install `yalc` globally with `npm i yalc -g` or `yarn global add yalc`
2. Run `yarn build` in your local `prosemirror-elements` from this branch
3. Run `yalc publish` in the same directory
4. Run `yalc add …

feat: Create rich-link element 

---

package.json
src/editorial-source-components/Tooltip.tsx
src/elements/image/ImageElementForm.tsx
yarn.lock

This PR adds a tooltip to the image element which explains the purpose of alt text. It also links to an external document that goes into more detail about writing good alt text, with examples.
A user noticed an article (of mostly images) had a '.' for all its alt text fields - a user circumventing the minimum character rule for alt text in Composer.
Any minimum character rule can be worked around, so it was decided that adding a tooltip explaining that alt text is valuable for users of assistive technology would be a good behavioural nudge, and useful to users of Composer who might want a refresher on its purpose.
I ran a query on our database and found that, of 1,499,519 images used in articles, 16,050 had alt text of less than 5 characters (which are unlikely to be good image …

feat: Add alt text tooltip

---

package.json

Removes the `engines` field – this was added to ensure, along with `.nvmrc`, that we were developing in consistent environments, but this field is also used by `npm` module consumers to [ensure our code is run in the correct node environment](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines). That's something that our output, which is built for client side consumption, doesn't have an opinion about.

chore: Remove engines field

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts

Updates the editor selection when the user focuses empty Prosemirror-based fields.
We must do this manually, because Prosemirror does not dispatch a transaction when this occurs in an empty editor. This makes sense for a root editor, because it's effectively a no-op from a state point of view – but for nested editors, this does result in a change of state!
- The new integration test should pass, and you should be convinced it reflects the correct behaviour.
- Open the demo page, create an element with a text field, open the dev tools, and click into empty text fields. You should see the selection update.

fix: Update selection manually when nested text fields are focused

---

src/elements/embed/embedComponents/Preview.tsx

This PR changes the height of the preview in the embed element.
Instead of having a fixed size, the preview dynamically resizes based on its content, up to a size of 100px. After reaching that cap, the preview can be manually resized further. (It will remain in resizeable mode until the page is refreshed)
Run `yarn start` from this repository locally. Add some html to the `embed code` field. Does the preview appropriately resize?

feat: Resize embed preview on content height change, allow manual resize over 100px

---

demo/index.ts
src/elements/embed/EmbedForm.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/embed/embedComponents/EmbedRecommendations.tsx
src/elements/embed/embedComponents/embedUtils.ts
src/index.ts

Types the embed callback conversion urls with template string literals, per @davidfurey's suggestion.
Typechecking with these types in the consuming context (see `demo/index.ts` below) should not cause a compile error.
I can't see a way of refining on the string such that I can achieve this without coercing with `as` – is this possible?

feat: Type callback urls for automatic embed creation

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.spec.ts
src/editorial-source-components/FieldWrapper.tsx
src/editorial-source-components/InputHeading.tsx
src/plugin/__tests__/plugin.spec.tsx
src/plugin/plugin.ts

This PR fixes a small bug which was causing sub-optimal performance and also a validation bug. The validation bug would manifest as a delay between changes being made to content and the validation updating. I.e. in a required field adding a single character wouldn't set the state to valid, you would then have to make an additional edit to the element.
Make changes to elements which would cause it to be come valid or invalid, ensure that these validation warnings displayed when intended.

fix: Element validation delay bug by reversing ternary

---

src/elements/rich-link/RichlinkForm.tsx

At the moment the rich-link element does not open the depressed hyperlink in a new tab/window.
This simple PR adds the behaviour to open the selected hyperlink to replicate the current rich-link element in Composer
Run locally or in code and add a rich-link - trying to click on the link to see the behaviour

feat: add target _blank behaviour to open in new tab

---

src/plugin/helpers/validation.ts

This PR Reverts guardian/prosemirror-elements#148. This is because we now perform our validation more [efficiently within Composer](https://github.com/guardian/flexible-content/pull/3929), this should allow us to include the original less performant deserialising HTML checks without compromising our application.
Does the validation still work as expected? Does linking the package to Composer result in performance issues?

fix: Reintroduce deserialisation to HTML for required or length checks

---

README.md
package.json

This PR adds a convenience script for creating a new build and distributing it locally via `yalc`. This should make it easier to work. 
I decided this would be a useful addition after being caught-out by publishing the package without first creating a local build meaning my changes weren't reflected in the consuming project.
Does running `yarn yalc` create a new build of the package and distribute it via yalc?

feat: Adds Yalc package script

---

src/elements/image/ImageElement.tsx
src/plugin/fieldViews/RichTextFieldView.ts

Adds Typerighter attrs to the image caption.
Run locally. Is the `useTyperighter` attribute set for the image caption node?
N/A

feat: Add typerighter attrs to image caption and alt text

---

src/elements/image/ImageElementForm.tsx

This PR fixes an issue with the "role" filed not being correctly set for images with small assets. Prior to this PR, the role setting would remain as the default until the element crop was changed. This meant if you added an image with small assets, the role would be incorrectly set but still display the weighting as "thumbnail". 
This PR fixes the issues by checking asset changes (including when a new image element is added) and sets the role to "thumbnail" if they are too small. This is done by using a `useEffect` in the `ImageView` component. 
Add an image with dimensions less than 460 pixel to the sandbox environment. Use the ProseMirror dev tools to confirm the role is correct set to "thumbnail".

fix: Fixes small crop, role setting bug

---

src/elements/image/ImageElementForm.tsx
src/elements/image/imageElementDataTransformer.ts

_co-authored-by: @SHession_ 
Our current implementation of the thumbnail constraint logic violates a lifecycle constraint under certain conditions in our rich text editor. This switches to another implementation that shouldn't be able to produce this bug.
- Does the image addition/recrop behaviour behave as expected?
- Does the bug still exist in our CMS?
Tested w/ @SHession in Composer:
- initial image is too small
- recrop is too small
- regular image

fix: Fix the thumbnail update issue

---

src/elements/helpers/Preview.tsx

The Preview used by Embed element had a max height set, after which the Preview could be manually resized, but would not automatically expand.
However, we have decided to remove the limit in order to be consistent with the existing element. The height taken up by embed previews has not been raised as a problem by our users, so we feel it is probably not worth adding the functionality.
|---|---|
| ![2022-01-25 15 15 13](https://user-images.githubusercontent.com/34686302/151004354-10677277-acc6-44a1-b1fe-d636b12cd3ce.gif) | ![2022-01-25 15 14 17](https://user-images.githubusercontent.com/34686302/151004374-3cf4d5b8-790d-4da9-b55b-4ffbf7b3b373.gif) |
(n.b. Other differences here are down to differences between Composer CODE (left) and the `prosemirror-elements` demo …

feat: Remove Preview height limit

---

src/editorial-source-components/Button.tsx
src/editorial-source-components/Description.tsx
src/editorial-source-components/Error.tsx
src/editorial-source-components/Label.tsx
src/plugin/__tests__/plugin.spec.tsx
src/plugin/elementSpec.ts
src/plugin/nodeSpec.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/ElementWrapper.tsx

Adds a selected state to the element node attributes, and surfaces this state in our renderer to allow the UI to respond.
Before:
https://user-images.githubusercontent.com/7767575/150793398-c17e6c17-ec19-4366-a7ab-7cb22d9f6b07.mov
After (updated to reflect `user-select: none`):
https://user-images.githubusercontent.com/7767575/151000747-2ec0b7d8-b4e4-4e46-8b1c-29e54b0daa44.mov
I've based it on the Chrome and Firefox selection colour for now 😅 we could pass it in on element creation if we really wanted to provide a way to customise, or perhaps there's another way to do it.
Incidentally, Chrome will automagically change the highlight colour when there's no contrast with the background colour, hence selection outlines showing in the labels and validation. We _could_ remove those with …

feat: Add state management and UI for selected Elements

---

src/elements/embed/embedComponents/__tests__/embedDataTransformer.spec.ts
src/elements/embed/embedDataTransformer.ts
src/elements/helpers/__tests__/html.spec.ts
src/elements/helpers/html.ts

This PR alters the embed's output, to more closely match the pre-existing setup. The intention is to reduce the chance of downstream bugs caused by a change in behaviour.
The following elements are now optional:
- `alt`
- `caption`
- `url`
There is now also an `isSafe` field. This checks if the html is for a single iframe, replicating a check that came from our [fence](https://github.com/guardian/fence/blob/9448f9a059d3264dfe0b3f3465cbacb498b3ffe9/fence.js#L139) package.
Run the unit tests locally with `yarn:test-unit`

fix: Make alt, caption and url optional for embed, add isSafe field

---

cypress/helpers/editor.ts
cypress/tests/ElementWrapper.spec.ts
src/plugin/helpers/prosemirror.ts

Currently when an element is deleted in the document the `focus` is `blurred`; the document/view is no longer active.
Therefore pressing `ctrl+z` to undo the delete and re add the element does not do the trick as we are no longer 'in the doc'.
The `focus` upon deletion moves away from (it is `blurred`) the document `view`, the editable part of the document/editor is no longer selected. 
Therefore the undo only works if you manually click where the element was in the document/editor first, which is less than desirable.
This PR therefore aims to automatically add focus to the editor once the element is deleted allowing for the undo to re add the element. 
- we have added integration tests with Cypress to check for succesful re focussing within the document `view` upon deletion.
1. Tested in …

feat: `focus` editor after element removal

---

demo/index.ts
src/elements/embed/EmbedForm.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/helpers/ThirdPartyStatusChecks.tsx
src/elements/interactive/InteractiveForm.tsx
src/elements/interactive/InteractiveSpec.tsx
src/elements/video/VideoForm.tsx
src/elements/video/VideoSpec.tsx

There was a mixture of variable names related to third party tracking in the `EmbedElement` and `InteractiveElement`. This PR updates all the relevant variables to refer to `ThirdPartyTracking` rather than `EmbedTracking`.
This will change the interface of the object expected by the `createEmbedElement` and `createVideoElement` functions to require a `thirdPartyTracking` property rather than an `embedTracking` property. As this is the main interface for that element with outside consumers (e.g. flexible-content) this could be considered a breaking change.
However, the Embed and Video elements are still in testing, so perhaps we can avoid the major version bump on that basis. Interested in the thought of reviewers on this.
Run the application locally with `yarn start`. Run the tests with …

feat: Rename all tracking-related variables to use consistent naming

---

src/elements/image/ImageElement.tsx

This PR updates the placeholder text for the image element's alt text field - giving a more direct prompt to the user, based on a suggestion by @pradasa.
| --- | --- |
| `Enter some alt text…` | `Describe the image for visually impaired readers` |

feat: Update image alt text placeholder to prompt for accessible text

---

src/editorial-source-components/SvgCrop.tsx
src/elements/image/ImageElementForm.tsx

This PR updates the image element re-crop icon from a camera to a conventional crop icon.
Before:
After:
Checkout this branch, does the icon display correctly?
Users have a clear, more intuitive understanding of what the button does.

feat: Uses "crop" icon for image re-crop button instead of "camera" icon

---

src/elements/embed/embedComponents/__tests__/embedDataTransformer.spec.ts
src/elements/embed/embedDataTransformer.ts

After the embed feature switch was turned on by default, [problems were reported with email newsletter embeds.](https://github.com/guardian/flexible-content/pull/3994). 
We deduced that this was due to a misnamed field - the `safeEmbedCode` field, which was instead called `isSafe`. This led to areas of the frontend wrapping iframe embeds in an additional iframe, leading to styling problems.
This PR gives that field the correct name.
Run the application and its tests according to the instructions in the readme.

fix: Use correct name for 'safeEmbedCode' field

---

cypress/tests/ElementWrapper.spec.ts
demo/style.css
src/editorial-source-components/SvgHighlightAlt.tsx
src/plugin/helpers/prosemirror.ts
src/plugin/nodeSpec.ts
src/plugin/plugin.ts
src/plugin/types/Commands.ts
src/renderers/react/ElementWrapper.tsx

This attempts to improve the select-ability of elements by providing a convenient button which will select the element. This should make working with them much simpler, improving the workflows for copying, cutting and deleting elements. It should also improve how intuitive it is for changes to be undone and redone. See the video for an illustration of these effects.
https://user-images.githubusercontent.com/4633246/152768970-1034d24c-9714-48b2-b607-f984eed89d9a.mov
This PR can be tested in the sandbox environment using this branch. I have also created a [branch in Composer](https://github.com/guardian/flexible-content/compare/pme-selectable-elements-beta?expand=1) using a beta release to see the finished product. 
It provides a new and intuitive way to interact with elements.
This may …

feat: Add element select button

---

demo/index.ts
src/elements/helpers/transform.ts
src/elements/interactive/InteractiveSpec.tsx
src/elements/interactive/__tests__/interactiveDataTransformer.spec.ts
src/elements/interactive/interactiveDataTransformer.ts

This PR includes the interactive element in `transform.ts`, which means it can properly interact with `flexible-content`.
It also:
- updates its fields to better reflect the data fields of the existing interactive element, which reduces the risk of problems downstream of `flexible-content` 
- updates the demo element to import the interactive more consistently with the other elements.
- Includes tests for the `interactiveDataTransformer`
This should not affect the running of `prosemirror-elements`, only update its API - though you can run the application and test the demo locally following the instructions in the readme, or run the tests with `yarn test:unit` or `yarn test:integration`.

feat: Include interactive in transform.ts

---

demo/index.ts
src/elements/embed/Callout.tsx
src/elements/embed/CalloutForm.tsx
src/elements/embed/EmbedForm.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/embed/embedComponents/__tests__/callout.spec.ts

Co-authored with @SHession 
This PR adds the Callout. This is rendered when the `html` field of an Embed element contains the string "data-callout-tagname".
I've taken the opportunity to make the Callout's UX more useful.
In Composer, the user doesn't get much feedback from the old Callout: 
This makes it hard for a user to understand what the element actually represents, or whether it's working as intended.
The new Callout fetches information from [Targeting](https://targeting.gutools.co.uk/) - the same information that is used by platforms to render the Callout in articles.
There are also two error states representing:
- a failure to find a callout matching the tag
- a failure to parse a tag
(Previously these would silently fail)
We recently turned on the Embed element's feature switch. …

feat: Add the Callout

---

src/editorial-source-components/Editor.ts

Currently elements with warnings for presence/length checks render a red wanring message, however the red border around the input box is not present.
This PR aims to fix the CSS overriding issue in conjunction with the PR in `flexible-content`: https://github.com/guardian/flexible-content/pull/4006
Running Composer Locally and creating a Pullquote element and ensuring that there is a red border around the input box along with the red warning text

feat: adds warning styling to element border

---

demo/index.ts
src/elements/rich-link/RichlinkForm.tsx
src/elements/rich-link/RichlinkSpec.tsx

Currently the behaviour for the rich link identifies whether the article which is being linked has been published or is in draft/preview mode.
However the new rich link element does not, this PR aims to amend this by adding:
- `draftReference` as in the rich link spec to communicate the status to Composer
- Styling to the element which renders a warning message to the user
- New style for warning designed by Ana Pradas - https://www.figma.com/file/Ji1XENAJJjzcxwwwfWZnJc/Embeds?node-id=606%3A5771
1 - Create an article in Composer up to a publishable state - but do not publish
2 - Create/open another Composer article
3 - Add the (non published) URL as a rich link in the new article and at this point the warning message will render
4 - Add a URL of an existing published article to see that …

feat: ds/rich-link warning unpublished article

---

src/elements/rich-link/RichlinkForm.tsx
src/elements/rich-link/RichlinkSpec.tsx

- Removes the warning container to ensure warning text wraps
- Ensures that draftReference is absent in output data when it is an empty string, for consistency with PROD
- Add a draftReference to the rich link creation function in `demo/index.ts`, and check that the text wraps
- It's actually quite difficult to test the draftReference w/o using it in consuming code! You'll need to use `yalc` to confirm. Alternatively, merge with #196 locally and observe the output data.
Consistency w/ our current setup.

feat: Minor amends to rich text element

---

demo/index.ts
src/elements/embed/Callout.tsx
src/elements/embed/EmbedSpec.tsx

This PR changes the Targeting URL used by the Callout if the environment is local or CODE.
The following will use [Targeting CODE](https://targeting.code.dev-gutools.co.uk/):
- https://composer.local.dev-gutools.co.uk/
- https://composer.code.dev-gutools.co.uk/
- https://prosemirror-elements.local.dev-gutools.co.uk/
The following will use [Targeting PROD](https://targeting.gutools.co.uk/):
- https://composer.gutools.co.uk/
This will match the tags provided by Composer's environments (e.g. CODE/local Composer use tags from Targeting CODE).
Run locally following the instructions in the readme and add a callout element.
Does the callout correctly find callouts from [Targeting CODE](https://targeting.code.dev-gutools.co.uk/)?

feat: Callout - use targeting url matching environment

---

demo/helpers.ts
demo/index.html
demo/index.ts
demo/style.css

Adds a data pane, to make it easy to see what the data our elements  produce once they're run through our transformer.
When elements aren't recognised, they produce `null`.
Along the way, updates our layout with a few ergonomic bits and pieces: the top buttons are now sticky, and each pane for content and data now scrolls independently.
Have a play. Does the pane perform as expected? Is it useful?

docs: Add data pane to show transformed element data

---

.github/workflows/node-js.yml
.github/workflows/semantic-pr.yml

Pins our semantic-release related GHAs, which are third party actions, to a particular commit hash, in line with the security advice for [third party actions.](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
- Does the release portion of the github action still run as expected?
- Does the PR linting still run as expected?

chore: Pin 3rd party actions to specific commit hash

---

src/elements/helpers/__tests__/fixtures/index.ts
src/elements/helpers/__tests__/fixtures/rich-link.json
src/elements/helpers/__tests__/transformFixtures.spec.ts
src/elements/helpers/test.ts
tsconfig-esm.json

Adds fixture-based tests for element data, with an example dataset for the rich-link element.
These tests allow us to pull data from Composer and roundtrip it through prosemirror-elements. Here's a sample SQL query:
```sql
SELECT element
FROM livecontent, jsonb_array_elements(content -> 'blocks') as blocks,
jsonb_array_elements(blocks -> 'elements') as element
WHERE elements->> 'elementType' = 'embed'
LIMIT 100
```
We've been caught by small differences in our data before, and these tests should help make these differences visible before we ship new elements.
We have to compromise in a few places because it's sometimes reasonable for our data to be modified by this library:
- some rich links are missing a `role` field, which we supply by default
- some rich links are missing an …

chore: Add fixture based tests, and fixtures for rich-link element

---

src/plugin/__tests__/plugin.spec.tsx
src/plugin/fieldViews/AttributeFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/helpers/element.ts
src/plugin/helpers/fieldView.ts
src/plugin/plugin.ts

At the moment, we have two ways of serializing nodes representing fields into the values they represent:
- A method, `getElementDataFromNode`, which does what it says on the tin
- Instance methods on each `FieldView` instance, `getNodeValue`, which given a field node pass back data.
Although they're called in different contexts and with different sorts of data, they both at root do the same thing – translate node representing field data into the data itself.
We should only have one way of doing this. I've consolidated both ways into a single method, `getFieldValueFromNode`, and removed the relevant method(s) from our `FieldView` interface.
This fixes a problem where we treat text nodes as rich text on serialisation within the renderer, which means we're incorrectly escaping HTML chars in …

fix: Consolidate two methods of moving from node -> field data

---

src/elements/embed/Callout.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/embed/embedComponents/__tests__/callout.spec.ts
src/elements/helpers/Preview.tsx
src/elements/helpers/__tests__/html.spec.ts
src/elements/helpers/html.ts

Following up #217, this PR updates our elements to avoid unescaping HTML as it's rendered, by removing the escape step from the `parseHtml` function.
This was necessary because we were mistakenly escaping non-rich-text – now, that's no longer necessary, so #217 breaks any functionality that previously escaped text content.
- The automated tests should pass – we have tests for html parsing and detecting callouts that are affected by this change.
- Create an interactive. The preview should be visible.
- Create an embed. The preview should be visible. Adding an iFrame to a youtube video should work as expected (e.g. `<iframe width="560" height="315" src="https://www.youtube.com/embed/cCOL7MC4Pl0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; …

fix: Do not escape html anymore – it has already escaped

---

demo/index.ts
package.json
src/elements/helpers/types/TelemetryEvents.ts
src/elements/image/ImageElementForm.tsx
src/elements/image/imageElementTelemetryEvents.ts
src/plugin/__tests__/elementSpec.spec.ts
src/plugin/element.ts
src/plugin/elementSpec.ts
src/plugin/helpers/prosemirror.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/TelemetryContext.ts
src/renderers/react/createReactElementSpec.tsx
yarn.lock

The PR aims to add some basic telemetry in order to improve the observability of how our users interact with elements.
It makes use of the new [Ed Tools telemetry package](https://github.com/guardian/editorial-tools-user-telemetry-service/pull/10) to achieve this, and adds telemetry events to the element commands only. 
We will likely want to expand this API so users can add their own telemetry events to elements.
Add an element in the sandbox environment, interact with the element using the wrapper buttons (move arrows, select and delete). Observe outgoing network requests to the telemetry endpoint (i.e. "example.com").
We have visibility of user's interacting with element commands.

feat!: Adds basic telemetry sending functionality

---

.github/workflows/build-and-release.yml
package.json
release.config.cjs
yarn.lock

_co-authored-by: @SHession_ 
Moves our semantic-release setup out of github action into package.json script. There are two reasons:
- We must configure our release to match our PR linter, and this was not straightforward with the GHA
- It's better not to have 3rd-party actions at all, for security reasons.
Take a look at the [recent runs](https://github.com/guardian/prosemirror-elements/actions/runs/1980314132) on the `beta` branch. They should:
- result in a release
- respect the `!` suffix to the commit prefix, which indicates that they're using the `conventionalcommits` preset, proving our configuration works.
Less confusion when issuing breaking change releases, and one fewer third party dependency in our actions. (Still a dependency in our package.json, mind!)

chore: Move semantic-release out of github action into package.json script

---

.github/workflows/build-and-release.yml
release.config.cjs

#223 is missing a few plugins in our semantic release configuration that we need to publish to NPM, issue a release in Github, and fancy up our release notes.
This PR adds those changes.
Take a look at the `beta` branch., which contains these changes. Is there a new release in `npm` as a result of the push?
Releases work as before.

chore: Add additional plugins to release to npm and github

---

README.md
src/elements/helpers/__tests__/fixtures/content-atom.json
src/elements/helpers/__tests__/fixtures/parse-element.js

Adds a script to sanitise element fixtures as we generate them, parsing the element data out of string format and redacting certain fields that we'd prefer not to commit to a public repository.
Also includes data for the `content-atom` element, currently WIP.
- Does the script describe itself adequately?
- Stretch goal – can you use it on a given dataset? (Happy to supply example data! It's been used to create all of the fixtures we currently have)

chore: Add a script to sanitise element fixtures

---

demo/index.ts
src/elements/interactive/InteractiveForm.tsx
src/elements/standard/StandardForm.tsx
src/elements/standard/StandardSpec.tsx

Makes the 'standard' element a little nicer across the board:
- Moving the fields about to be more consistent with other elements
- Providing a 'preview' heading in line with the interactive and embed elements, which can contain the original content link
- Providing a large preview for documents, which were previously unreadable
|Before|After|
|--|--|
|<img width="1012" alt="Screenshot 2022-03-15 at 15 50 15" src="https://user-images.githubusercontent.com/7767575/158815475-aec20de6-ad29-4be8-916a-0672ffa472cf.png">|<img width="598" alt="Screenshot 2022-03-17 at 13 04 24" src="https://user-images.githubusercontent.com/7767575/158815601-a1e69686-6d0c-404a-b25c-a3e2b89d47f6.png">|
|<img width="974" alt="Screenshot 2022-03-15 at 15 50 24" …

feat: Rearrange standard element

---

src/elements/helpers/ThirdPartyStatusChecks.tsx
src/elements/helpers/__tests__/ThirdPartyStatusChecks.spec.tsx
src/elements/helpers/__tests__/html.spec.ts
src/elements/helpers/html.ts

Following up on #218, we no longer need `unescapeHTML`.
This PR removes it completely, and the one place where it was still used, the third party tracking code, which fixes a bug where unnecessarily escaping the HTML sent to this function meant we were sending malformed data to our tracking callback.
- The automated test added to test `ThirdPartyTracking` should fail before this change, and succeed afterwards.

fix: Remove unescapeHTML, as it's no longer used

---

src/elements/deprecated/DeprecatedForm.tsx

Improves our deprecated element description after feedback.
|Before|After|
|--|--|
|<img width="828" alt="Screenshot 2022-03-28 at 16 16 39" src="https://user-images.githubusercontent.com/7767575/160430756-fb1161d0-271c-4b5c-893d-a5ad9b86c414.png">|<img width="828" alt="Screenshot 2022-03-28 at 16 15 26" src="https://user-images.githubusercontent.com/7767575/160430767-c3ac5459-4909-4a0d-b9b2-8703d6139836.png">|
Take a look above, or in the sandbox. All ok?

fix: Improve deprecated element description

---

demo/index.ts
src/elements/deprecated/DeprecatedForm.tsx
src/elements/standard/StandardSpec.tsx
src/elements/table/TableSpec.ts

Comparing elements in Composer, table, audio, document and map elements permit the thumbnail role. This PR adds the thumbnail role to the table element, and the ability to remove the thumbnail role from a standard element, adding it by default (as the majority of elements using the standard template do have it).
It also sneaks in a minor change to the deprecated element copy, in line with recommendations from stakeholders.
Take a look at the video, table, audio, document and map elements. Video shouldn't have a thumbnail. Everything else, should.

fix: Add thumbnail to table element, and conditionally add thumbnail to standard elements

---

package.json

As part of an npm audit, I'm adding gh links to package jsons that don't already include them if this repo is being published
Adds a link to the source code.

chore: Include repo url in package.json

---

demo/index.ts
src/elements/content-atom/ContentAtomForm.tsx
src/elements/content-atom/ContentAtomSpec.tsx
src/elements/helpers/__tests__/transformFixtures.spec.ts

We used to have a feature where we checked an atom's publication state, but this was dropped for unknown reasons. This PR revives that feature and expands on the state check.
We now check for two states: whether the atom is published at all, and if it is published, whether or not there are unpublished changes available in Preview.

feat: Improves publication checks

---

demo/sampleElements.ts
src/elements/form/FormElementForm.tsx
src/elements/form/FormElementSpec.tsx
src/elements/form/formTransformer.ts

Makes a few changes as a result of testing in our CMS:
- Adds the 'required' validation to the form element, something that I didn't spot in #242. It's at a `WARN` level to match the current behaviour in our CMS, where this error does not prevent publication. 
- Corrects the 'edit' link, which was reasonably assumed to be `originalUrl`, but this doesn't link to an editable entity in formstack.
- Opens the edit link in a new window when clicked.
Add a form element. Are the above addressed?

fix: Add 'required' validation to form element

---

cypress/tests/ImageElement.spec.ts
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/helpers/keymap.ts
src/plugin/helpers/prosemirror.ts

<kbd>Mod-a</kbd> (i.e. <kbd>ctrl-a/cmd-a</kbd>) currently selects all Prosemirror elements when used within an element. 
This PR means that using <kbd>mod-a</kbd> within a text field selects only that field's text. 
1. Run prosemirror-elements locally following the instructions in the readme.
2. Create an element, click on a text field, type some text in an element and use <kbd>Mod-a</kbd>.
3. Try this in both rich text field (e.g. the image caption) and non-rich text fields (e.g. the pullquote)\
Does this select all of the the text in the field?
| --- | --- |
| ![2022-05-04 15 07 01](https://user-images.githubusercontent.com/34686302/166886190-a3655ecf-b474-4bec-8d26-a22d543436cd.gif) | ![2022-05-04 14 49 52](https://user-images.githubusercontent.com/34686302/166886227- …

feat: Mod-a within field selects only that field's text

---

src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/RepeaterFieldView.ts
src/plugin/helpers/fieldView.ts
src/plugin/nodeSpec.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts

Adds a field of type `repeater` to our `NodeSpec` generation.
A repeater field is a field that contains 0-many children, each containing their own set of field descriptions. We can imagine it being used to implement any field that includes repeated content – for example, a photo gallery, or tabular data.
This PR is a step in this direction, providing the necessary userland field creator, and modelling that field within Prosemirror. Subsequent PRs will need to flesh out:
- how this new field type interacts with field values as they are passed in and out of the RTE
- how this new field type is represented as a field within the renderer
- adding the ability to add, remove, and possibly move repeater node children in relation to their parent.
There are two ways I could think of to model our …

feat: [repeater PR 1] Add repeater field to NodeSpec

---

demo/index.ts
demo/sampleElements.ts
src/elements/content-atom/ContentAtomForm.tsx

Adds additional weighting options for interactives to match the behaviour of the element this replaces.
The old options looked like:
Running locally, or in Composer via `yalc`, add an interactive element to the document – I've added a new button, `Add interactive atom`, to make testing easy. Compare with other atoms by adding a Recipe atom in the same way. You should see that role options for non-interactive atoms have not changed, but interactive atoms now have the full gamut of options, as in this video: 
https://user-images.githubusercontent.com/7767575/175502697-d95cc0ed-2d35-4f9c-afed-5c624ba4cb2d.mov

feat: Add options for interactives

---

src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/nodeSpec.ts

This changes the structure of the default value that Prosemirror sets for custom node attributes to a format that composer API understands. The current format is causing save requests to fail. 
You can see this happening in composer when pressing the up-arrow underneath a pull-quote element and then typing in some text:
https://user-images.githubusercontent.com/33927854/178706419-4997e148-a3cd-4071-9316-414527a68912.mov
After the fix:
https://user-images.githubusercontent.com/33927854/178711752-cdbef638-fef5-426c-b4c6-9706f586edeb.mov
We suspect this is caused by an edge case where we do something unexpected (in this case, trying to type free text into a drop-down field) which triggers Prosemirror to try to recreate the element using its defaults.
Note, this does not fix the unexpected …

fix: change default value of custom node attributes to something composer API understands

---

docs/troubleshooting.md

Adds some advice on a possible culprit if a release is not triggered after merging a PR.

docs: adding troubleshooting docs

---

src/elements/helpers/defaultTransform.ts
src/elements/rich-link/RichlinkSpec.tsx

The Tweet element was not preserving changes to its 'Is required' field on refresh in Composer.
This PR makes sure that works, by transforming the 'isMandatory' field in and out of `prosemirror-elements`. Once this change is released, we can bump the version used by `flexible-content` to get the Tweet Element working there.
1. Run `prosemirror-elements` locally according to the instructions in the readme, and toggle the data view on.
2. Add a Tweet element, and change the 'isRequired' field. Does the data view also update?
3. Install `yalc`, and run `yarn yalc` in `prosemirror-elements` locally.
4. Run `flexible-content` according to the instructions in its repo. Install your local `prosemirror-elements` branch with `yalc add @guardian/prosemirror-elements` in the Composer directory (and …

fix: Tweet element fix

---

demo/sampleElements.ts
src/elements/callout/Callout.tsx
src/elements/embed/Callout.tsx

Paired on this: @marjisound & @abeddow91 
We currently have two callout components which should share the same type. This PR export the types from the `callout/callout` element component so that they can be shared by the `embed/callout` element. 
These changes were requested in https://github.com/guardian/prosemirror-elements/pull/270
Add a callout and a campaign callout and ensure there are no runtime errors.

refactor: consolidate callout types

---

src/elements/callout/Callout.tsx
src/elements/callout/CalloutTable.tsx
src/elements/callout/calloutDataTransformer.ts
src/elements/helpers/transform.ts

paired on with @abeddow91 & @marjisound 
This PR adds a custom callout transformer to transform the checkbox boolean to string and "none-selected" to undefined.
It also 
- updates the callout UI
- adds in a isNonCollapsible checkbox
This can be tested locally via a yalc link in Composer.

feat: add callout transformer and update callout ui

---

demo/index.ts
src/elements/callout/Callout.tsx
src/plugin/elementSpec.ts
src/plugin/helpers/element.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/__tests__/createReactElementSpec.spec.tsx
src/renderers/react/createReactElementSpec.tsx

_NB: depends on #278 – please review that first!_
This PR adds a `onRemove` prop for `createCalloutElement`. `onRemove` is a handler for when the element is deleted. The parameter passed to the handler is of type `FieldNameToValueMap` which includes all the element field values. 
To be able to pass field values to onRemove, the `elementSpec.ts` was updated in order to have access to element data at render stage. 
This was tested both with prosemirror demo and also with composer locally.

feat: Add an onRemove callback, which is called with the removed element's field data

---

demo/index.ts
src/editorial-source-components/FieldWrapper.tsx
src/editorial-source-components/InputHeading.tsx
src/editorial-source-components/Label.tsx
src/elements/callout/Callout.tsx
src/plugin/elementSpec.ts
src/plugin/fieldViews/AttributeFieldView.ts
src/plugin/fieldViews/CustomFieldView.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/AttributeFieldView.spec.ts
src/plugin/helpers/element.ts
src/plugin/plugin.ts
src/plugin/types/Element.ts
src/renderers/react/ElementProvider.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/__tests__/createReactElementSpec.spec.tsx
src/renderers/react/createReactElementSpec.tsx

#275 requires some React-based unit tests, but in order for `testing-library` to pass tests using our React wrappers, our accessibility story for labels needed to be improved, or we get the error:
```
Found a label with the text of: field1, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.
```
(How lovely for a testing library to point that out!)
This PR adds a test that verifies the accessibility of our labels by proxy, and adds the functionality that satisfies the test. Because we cannot add a `for` attribute to our label (`contenteditable` elements cannot be addressed by this attribute [per the spec](https://stackoverflow.com/questions/54792126/html-label-with-for-div-id-to-focus-a-contentedit …

feat: Improve label accessibility

---

.eslintrc.cjs
demo/index.ts
src/elements/callout/Callout.tsx
src/elements/callout/calloutDataTransformer.ts
src/elements/comment/CommentSpec.tsx
src/elements/content-atom/ContentAtomForm.tsx
src/elements/content-atom/ContentAtomSpec.tsx
src/elements/embed/EmbedSpec.tsx
src/elements/embed/embedComponents/__tests__/embedDataTransformer.spec.ts
src/elements/embed/embedDataTransformer.ts
src/elements/helpers/defaultTransform.ts
src/elements/helpers/transform.ts
src/elements/image/ImageElement.tsx
src/elements/image/__tests__/imageElementDataTransformer.spec.ts
src/elements/image/imageElementDataTransformer.ts
src/elements/interactive/InteractiveSpec.tsx
src/elements/interactive/__tests__/interactiveDataTransformer.spec.ts
src/elements/interactive/interactiveDataTransformer.ts
src/elements/membership/MembershipSpec.tsx
src/elements/membership/membershipDataTransformer.ts
src/elements/standard/StandardSpec.tsx
src/elements/standard/standardDataTransformer.ts
src/elements/table/TableSpec.ts
src/elements/tweet/TweetSpec.tsx
src/index.ts
src/plugin/helpers/constants.ts
src/plugin/helpers/validation.ts

Removes a circular dependency caused by `undefinedDropdownValue` – this PR moves it to a `/constants` folder.
A ✅ in the CI should be enough to prove this is good.
Additional circular dependencies exist that mean we can't yet include a linting rule. This will be added in a follow up PR, #267.

chore: Remove circular dependency caused by undefinedDropdownValue

---

demo/sampleElements.ts
src/elements/callout/Callout.tsx
src/elements/callout/CalloutError.tsx
src/elements/callout/CalloutTable.tsx
src/elements/callout/CalloutTypes.ts
src/elements/embed/Callout.tsx

Displays a non-blocking error message if one of the following occurs:
1. The callout has not been selected. This is handled out-of-the-box and displays as a warn in composer. 
2. The callout has an active until that has expired.
3. The callout no longer exists in the list of available callouts. 
Error 1 - The callout has not been selected
- This can be tested in prosemirror or in composer by adding a callout but not selecting anything from the drop down.
- In composer,  there should also be a warn message when hovering over the publish button.
- The article should be publishable with this error.
Error 2 - The callout has not been selected
- This can be tested in prosemirror by selecting the expired callout from the list. It is more difficult to test in composer as we filter out expired …

feat: add error handling to callout

---

demo/index.ts
src/elements/callout/Callout.tsx
src/elements/callout/calloutDataTransformer.ts
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

Paired on this work with @jonathonherbert & @rebecca-thompson 
This PR adds a new field `tagId` for the Callout element. This fields doesn't exist in view and is only added for the purpose of data. The field will be populated by value when the user chooses a callout from the drop down. 
This PR also removes the `applyTag` & `onRemove` handlers from the `Callout` element. These handlers were being used in composer client to add/remove the relevant callout tag to the furniture. 
The approach of adding/removing the tags on the client was found to be flaky and unreliable, so we decided to take a different approach by updating the tags server side when saving the updated content to database.  The composer PR can be found here https://github.com/guardian/flexible-content/pull/4287
This was …

feat: add tagId field to callout and remove the applyTag & onRemove handlers 

---

demo/index.ts
src/elements/cartoon/CartoonForm.tsx
src/elements/cartoon/CartoonSpec.tsx
src/index.ts

The Cartoon element form has two fields ("Vertical padding" and "Background colour") that were migrated across from the old Comic generator tool, but after speaking with users we're pretty sure we don't need them. This PR removes them. It also moves the "Weighting" field to the row above so it's not sitting on its own. Finally, it renames `cartoonElement` to `createCartoonElement` for the sake of consistency. 
Run `prosemirror-elements` locally and click the "Add Cartoon" button. Note the fields are gone.
I've also updated the [testing branch](https://github.com/guardian/flexible-content/compare/bt/cartoon-element) in composer with the new name (`createCartoonElement`). ~~Annoyingly I wasn't actually able to get this working. I think my `yalc` might be broken.~~ (Update: @rebecca-thompson …

feat: Remove unnecessary fields from cartoon form

---

src/elements/helpers/defaultTransform.ts
src/index.ts

This introduces two small changes to facilitate this pr: https://github.com/guardian/flexible-content/pull/4333.
The first is to export the `setMedia` type, so we can use it in Composer.
The second is to make `isMaster` an optional field in the Asset type. This is due to a type mismatch in Composer which is masked when the code using it is written in Javascript, but becomes apparent when it gets migrated to Typescript. The `isMaster` field does not appear on all assets, only the one that is the master asset. For all non-master assets the flag is absent altogether, rather than being `isMaster: false | undefined`.
You can build this library locally using `yalc` and test local Composer to see insert and recropping image elements continues to work as expected

fix: Export SetMedia and don't require `isMaster` field in assets

---

demo/helpers.ts
demo/index.ts
src/elements/cartoon/CartoonForm.tsx
src/elements/cartoon/CartoonSpec.tsx
src/elements/cartoon/__tests__/cartoonDataTransformer.spec.ts
src/elements/cartoon/cartoonDataTransformer.ts
src/elements/helpers/defaultTransform.ts
src/elements/helpers/types/Media.ts
src/index.ts

While testing the Cartoon element in Composer, images were temporarily added as a top level field called `elements`.
This PR moves these elements into the `fields` field. It also defines a type for `fields` based on the one from the ticket.
It's hard to measure success at the moment but this change should move us closer to how the data will actually be modelled.
There should be no risk as the cartoon element is not currently used anywhere.

feat: Update cartoon data transformer

---

src/elements/cartoon/CartoonForm.tsx

The new cartoon element has a bug the media url is used as a key for adding and removing images in the image array. This works unless multiple of the same image are added, then things start getting weird because the key is no longer unique which [react doesn't like](https://legacy.reactjs.org/docs/lists-and-keys.html).
The fix is just to append the array index to the media url to ensure uniqueness. React don't recommend doing this...
> We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state.
...however since re-ordering isn't possible in this context, just adding and deleting, this appears to be safe. I didn't observe any new bugs or performance issues when testing.
Follow [these …

fix: Fix indexing of cartoon images

---

demo/index.ts
src/elements/image/ImageElementForm.tsx
src/elements/image/imageElementValidation.ts

The image element currently derives its weighting drop down options (also referred to as 'role' in some places) from two places:
1. hard-coded values in the React component (thumbnail)
2. values that are passed in when the element is created - such as [here](https://github.com/guardian/flexible-content/blob/main/composer/src/js/prosemirror-setup/helpers/image-element.ts)
Up to this point, having the thumbnail weighting automatically added hasn't been a problem as all image elements allow for an image to be a thumbnail, however... the Picture content editor does not currently permit this weighting, so we need to move thumbnail from a hard-coded value and start passing it in along with the other weighting options.
This has been tested locally by running `yarn yalc` and importing the local …

feat: Stop adding the thumbnail role to all image elements

---

.github/workflows/build-and-release.yml

It looks like the default permissions for the `GITHUB_TOKEN` have changed underneath us, breaking the release stage of our CI pipeline. To see this in action (pun intended), you can see the permissions have changed from the last successful release and the most recent failed release:
| Original    | Current |
| -------- | ------- |
| ![Screenshot 2023-06-28 at 11 37 20](https://github.com/guardian/prosemirror-elements/assets/33927854/be5b02f7-56f3-44d3-8dcf-ebcb859a496c)  | ![Screenshot 2023-06-28 at 11 37 09](https://github.com/guardian/prosemirror-elements/assets/33927854/2f09f4ce-8fb9-4b59-89e8-da2fb2e66490)    |
The release stage of our CI pipeline is failing at the point at which is tries to publish tags to the repo. This pr gives the minimum required permissions by semantic-release …

fix: Give GH Actions the appropriate permissions to publish tags

---

.github/workflows/build-and-release.yml

There's a simpler way to setup node with the version specified in the .nvmrc file
Rather than cat'ing a file and using the output of steps, you can just list the file in the setup-node action
Reduces the number of steps, and makes the intention clearer in the workflow file

fix: Simplify-actions-node-version

---

src/plugin/fieldViews/ProseMirrorFieldView.ts

The `getNodeFromValue` function is called whenever we call `update` on a field from within one of our element forms. For example, the button to populate the alt text from the caption in `ImageElementForm.tsx`:
```
<Button
priority="secondary"
size="xsmall"
iconSide="left"
onClick={() => {
sendTelemetryEvent?.(
ImageElementTelemetryType.CopyFromCaptionButtonPressed
);
fields.alt.update(fields.caption.value);
}}
>
Copy from caption
</Button>
```
The problem with the way `getNodeFromValue` is currently implemented is the default behaviour is to parse the html into the default top node type (usually `doc`).
In the Picture content editor in flexible content, we have restricted the doc to have 0 or 1 elements of type image, so when it tries to parse text into the doc, it fails.
This can be …

feat: Update Node to correct type

---

demo/helpers.ts
src/elements/cartoon/CartoonForm.tsx
src/elements/cartoon/CartoonSpec.tsx
src/elements/cartoon/__tests__/cartoonDataTransformer.spec.ts
src/elements/cartoon/cartoonDataTransformer.ts
src/elements/helpers/types/Media.ts
src/index.ts

This changes the `displayCredit` boolean values in the cartoon data transformer to be correctly modelled as a boolean, rather than a string.
It also moves the definition of the `Image` type to be co-located with the other Media type definitions and exports this type, so we can use it in flexible-content (important for getting re-crop and add image buttons working).
This has been checked by building the libs locally using `yalc` and pulling them into the flexible-content project.

fix: model cartoon element booleans as booleans, not strings

---

demo/index.ts
src/elements/cartoon/CartoonForm.tsx
src/elements/cartoon/CartoonSpec.tsx
src/elements/cartoon/__tests__/cartoonDataTransformer.spec.ts
src/elements/cartoon/cartoonDataTransformer.ts

This adds a new field to the Cartoon element to define the `imageType`, defaulting to Illustration if not defined.
It also renames `credit` to `photographer` in the data but not in the UI were it is labelled `byline`. This was discussed out of band and decided to change the name to align with the Image element, even though the label photographer may be less relevant in the context of a Cartoon. The idea is to eventually change this field for both elements to something more generic (such as byline as it is labeled in the Grid) and migrate existing data across. 
Run `yarn start` to launch the local demo. The Cartoon element should continue to successfully populate the `Comic credit` field with the correct value and should have an additional drop-down field to set the image type.

fix: Add imageType to cartoon element and rename credit to photographer

---

src/elements/cartoon/CartoonForm.tsx

Adds the remove image cross after the image rather than before. This prevents images of certain dimensions from masking the cross.
| Before      | After      |
| ----------- | ---------- |
| <img width="168" alt="Screenshot 2023-08-15 at 09 50 46" src="https://github.com/guardian/prosemirror-elements/assets/33927854/ca946591-ece6-4f5e-aadc-78e3c74831bf"> | <img width="168" alt="Screenshot 2023-08-15 at 09 50 28" src="https://github.com/guardian/prosemirror-elements/assets/33927854/bb7ae64c-4443-4c08-a4a0-041c73a5be41"> |
You should be able to run the demo and add/remove images from the cartoon element with no trouble.

fix: formatting of cross to remove images in cartoon element

---

demo/index.ts
demo/sampleElements.ts
src/elements/helpers/transform.ts
src/elements/recipe/RecipeElementForm.tsx
src/elements/recipe/RecipeElementSpec.tsx
src/index.ts

Introducing an initial component for editing of Recipe type Elements using a prosemirror component.
Naive just edit the recipeJson in a text area developer UX.
Installing this component behind a Composer feature flag allows us to demo the end to end work flow for these elements.
This is independent of the larger refactor #313 to pull these components into Composer.
Introduce a new component and adds it to the demo page.
The recipe component is available to Composer, allowing changes to these elements to be round tripped through Composer.

feat: Introduce initial component for editing Recipe Element types

---

cypress/helpers/editor.ts
demo/helpers.ts
demo/index.ts
src/editorial-source-components/FieldWrapper.tsx
src/elements/callout/Callout.tsx
src/elements/demo-image/DemoImageElement.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/helpers/__tests__/transformFixtures.spec.ts
src/index.ts
src/plugin/fieldViews/CheckboxFieldView.ts
src/renderers/react/FieldComponent.tsx
src/renderers/react/customFieldViewComponents/CustomCheckboxView.tsx
src/renderers/react/customFieldViewComponents/CustomDropdownView.tsx

Exports the necessary helpers to create elements with `prosemirror-elements` – but not the library elements themselves.
We think it's better to define these closer to our CMS to improve the feedback loop when we're iterating on element structure and UI changes.
What we do with the elements as they stand in the repo can be addressed in a follow-up PR. I'd be tempted to keep a few definitions around as they're useful in the sandbox – but we might clearly label them to make it clear they're not used in production. (Not that they could be, as they are no longer exported?)
- The automated tests should pass.
- Take a look at the new exports in [index.ts](https://github.com/guardian/prosemirror-elements/blob/f095a75916f5a5cb153c3b20de14674c3012fafb/demo/index.ts) – all make sense?
- Take a look …

feat: Export element helpers, but not elements

---

.changeset/pretty-ducks-suffer.md
src/index.ts

Exports `createRepeaterField`, which should really have been in #313. 
You should be able to use `createRepeaterField` in consuming projects.

feat: Export repeater field

---

src/renderers/react/ElementWrapper.tsx

~Ameliorate erratum~
Actually the styles have been working fine all this time so probably better just to remove the style that hasn't been applied rather than cause unintended side-effects by fixing the typo.

Remove style that hasn't been applied due to typo

---

src/plugin/nodeSpec.ts

This adds typerighter support in repeater nodes by default. This means that the key takeaways element will support Typerighter.
1. Publish this branch locally with `yalc publish`
2. Use in the composer directory of flexible-content with `yalc add @guardian/prosemirror-elements`
3. Activate the key takeaways feature switch
4. Add some incorrect text in the content field of the key takeaways element
5. Run Typerighter (you may need to visit a CODE domain to be authorised)
6. Are the mistakes highlighted by Typerighter?

Support Typerighter in repeater nodes by default

---

src/elements/alt-style/AltStyleElementSpec.tsx
src/plugin/fieldViews/NestedElementFieldView.ts

This adds an option to specify the minimum rows for a `nestedElementField`.  This will allow us to hint to Composer users that a field is intended for multiline text. `minRows` for the `nestedElementField` applies a `min-height` style to the relevant field using a calculation based on the browser's `line-height`.
I've added this to the `NestedElementField` rather than the `ProseMirrorFieldView` it extends because we haven't got a use case for `minRows` in the `RichTextField` yet (which also extends `ProseMirrorFieldView`) - additionally, the `TextField` (which already supports rows) also includes `maxRows` and `isMultiline` which I was reluctant to add as options for all text fields. I've avoided these questions by just adding `minRows` to the place where we definitely want it.
1. Run the …

Add minimum rows option for nestedElementField

---

.changeset/nervous-ligers-peel.md
package.json
yarn.lock

Bumps changeset version and moves it to devDependencies. This should resolve high Snyk vulnerabilities both in this project and in flexible-content

Fix high vulnerabilities

---

src/elements/alt-style/AltStyleElementForm.tsx
src/elements/alt-style/AltStyleElementSpec.tsx
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/fieldViews/RepeaterFieldView.ts
src/plugin/fieldViews/__tests__/RepeaterFieldView.spec.ts
src/plugin/helpers/fieldView.ts

Small tweak to #334 to make the `minChildren` an actual property of the repeater itself rather than an input/argument to `removeChildAt` function to reduce the possibility of misuse/bugs (greater encapsulation in other words).

make `minChildren` a property of the repeater itself (for greater encapsulation)

---

demo/index.ts
src/elements/alt-style/AltStyleElementForm.tsx
src/elements/alt-style/AltStyleElementSpec.tsx
src/index.ts

Co-authored-by: @twrichards 
Add-on to be merged into https://github.com/guardian/prosemirror-elements/pull/334 to expose a generic `createReactAltStylesElementSpec` which takes `fieldDescriptions` (must have `repeater` field) and `renderRepeaterChild` function as arguments and returns an element with the surrounding add/remove/move controls, for use with 'Key Takeaways' in composer for example.

make alt styles element (with controls) usable outside PME (e.g. in composer for 'Key Takeaways')

---

cypress/helpers/editor.ts
cypress/tests/AltStylesElement.cy.ts
cypress/tests/ImageElement.cy.ts
demo/index.ts
src/editorial-source-components/Editor.ts
src/elements/alt-style/AltStyleElementForm.tsx
src/elements/alt-style/AltStyleElementSpec.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/index.ts
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/fieldViews/RepeaterFieldView.ts
src/plugin/fieldViews/__tests__/RepeaterFieldView.spec.ts
src/plugin/helpers/fieldView.ts
src/renderers/react/AltStyleElementWrapper.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/WrapperControls.tsx

Paired on with @twrichards 
Previously we were able to add child nodes at the end of the repeater, and remove child nodes at a given index.
This PR allows us to add child nodes at a given index, and move child nodes up or down an index. It also refactors the remove method to have greater guards against invalid invocation (in line with the new methods), and renames the methods to be more precise.
You can play about with these controls by creating an Alt Style element in the demo:
Check that the controls work as expected, and are enabled / disabled in the right places.
There are also new tests for these methods which can be inspected and run to give confidence in the PR's intent.

Add more control over repeater child nodes

---

.changeset/beige-fireants-rush.md
src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/nodeSpec.ts

Worked on with @rhystmills.
This fixes a bug where you can 'delete' an element that requires one child, putting it in a broken state.
Publish the ProseMirror library locally and test in a consumer (e.g. Composer) where there is a repeater element with a `minChildren` property ≥ 1 (e.g. Key Takeaways). 
You should be able to delete the element (by hitting CMD + A and backspace, _not_ the controls as these are disabled).
Deleting the element will wipe all its content but crucially keep a repeater with one empty child.
The document should save as normal and fire no error messages.

Enforce repeater has minChildren nodes in schema

---

.changeset/twenty-pans-own.md
src/plugin/nodeSpec.ts

Text elements weren't saving and loading in flexible-content due to an inconsistency with naming. In flexible-content they have the `elementType` "text" but their internal `elementName` in prosemirror is "textElement".
This PR makes sure we recognise these nodes when we initialise the editor, and convert them to a "textElement".
I've tested this functionality locally.
Use this library in `flexible-content` using this branch and https://github.com/guardian/flexible-content/pull/4566

Fix bug with text element serialisation in nestedElement fields

---

.changeset/odd-garlics-live.md
demo/style.css
src/editorial-source-components/FieldWrapper.tsx
src/elements/alt-style/AltStyleElementForm.tsx
src/elements/alt-style/AltStyleElementSpec.tsx
src/plugin/helpers/constants.ts
src/renderers/react/AltStyleElementWrapper.tsx
src/renderers/react/ElementWrapper.tsx
src/renderers/react/WrapperControls.tsx

Before:
After:
We want more real estate for this type of element as it is closer to a document level item than an element level item. It also helps us deal with fitting our nested elements inside this element.
We now omit the headings for these fields because we want it to look closer to a document. We should consider adding better placeholders for these fields in a future PR (not trivial because placeholder logic is a bit of a muddle).

Widen alt style element

---

.github/workflows/build-and-release.yml

Ensured that we always build PRs, as PRs not onto main were not building, e.g. if you chaining multiple PRs together... e.g. 
Also added `workflow_dispatch` to allow for manually triggered workflows, also useful.

improve triggers for CI GHA

---

.changeset/shiny-poets-itch.md
package.json
yarn.lock

This PR adds a changeset for [Tom's fix](https://github.com/guardian/prosemirror-elements/pull/349) to the longstanding decoration bug for nested fields in repeater fields.
Some prosemirror packages have also been bumped, and these seem to be compatible with Composer when testing locally.
I did notice an unused package (`prosemirror-schema`) had been accidentally added. It [wasn't used anywhere in the project](https://github.com/search?q=repo%3Aguardian%2Fprosemirror-elements%20%22prosemirror-schema%22&type=code) so I've removed it. It was possibly added in the package bumping progress due to its similarity to `prosemirror-schema-basic`.
This should be a no-op, other than triggering a release PR via Changesets.

Create changeset for decoration fix in repeater nestedFields and remove unused package

---

cypress/tests/EventPropagationFromInnerEditors.cy.ts
demo/index.ts
src/plugin/fieldViews/NestedElementFieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/helpers/test.ts

https://trello.com/c/MhfcXb4t/2168-ensure-plugins-work-across-the-nestedelement-boundary-eg-noting-dragdrop-media-etc
Whilst reviewing #349 @Georges-GNM observed that when used in composer, notes weren’t individually clickable when inside a 'NestedElement` (i.e. an inner ProseMirror instance). This is because the [noting plugin](https://github.com/guardian/prosemirror-noting) operates on the top-level editor (and we don't re-register the plugin for inner editors as they instances of the plugin will essentially fight over the content).
Digging deeper, by utilising the debugger to view the call stack when interacting with notes in the top-level editor and comparing to interacting with notes in inner editors, the default `handleClick` for the inner editor was effectively eating the event and …

propagate click events upwards from inner editors (e.g. `NestedElementFieldView`) up to the top-level editor so that plugins work

---

.changeset/neat-guests-study.md
src/plugin/fieldViews/NestedElementFieldView.ts
src/plugin/plugin.ts

To be used in conjunction with https://github.com/guardian/flexible-content/pull/4645
This PR makes sure `nestedElement` fieldViews are always updated, as a workaround for a bug with the zipRoot plugin, that causes the document to be uneditable when an element is deleted between two text elements.
1. Use this branch locally with Composer using yalc.
2. Do all the things suggested in the other PR: https://github.com/guardian/flexible-content/pull/4645

Always update fieldView of nestedElement field

---

cypress/tests/EventPropagationFromInnerEditors.cy.ts
src/plugin/fieldViews/NestedElementFieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts

https://trello.com/c/Z3K0WT7D/2160-fix-shortcuts-eg-cmd-z-not-working-in-key-takeaways-elements
It has been noticed that none of the key mappings (e.g. undo, redo etc.) have been working inside Key Takeaways. This makes sense since key-mappings are a plugin and we know from the exploration which led to https://github.com/guardian/prosemirror-elements/pull/362 that events don't make it up to the top-level editor by default.
IMPORTANT: in #362 the click events were being forwarded up from ProseMirrorFieldView but doing the same for key events broke some tests for RTE, so moved the click event forwarding in #362 down to apply only to NestedElementFieldView
NOTE: the cypress test for undo/redo in the inner editors has been marked as 'skipped' since it wasn't working in CI (but was locally) …

propagate key down & press events upwards from NestedElementFieldView up to the top-level editor so key mappings work as expected

---

.changeset/shiny-rice-eat.md

Release this change: https://github.com/guardian/prosemirror-elements/pull/363

Release key event handling changes

---

.changeset/little-donkeys-float.md
src/plugin/fieldViews/NestedElementFieldView.ts

The [workaround](https://github.com/guardian/prosemirror-elements/pull/365) for the text element join after deleting a non-text element between two text elements relied on `nestedElement` fields having the content expression `element+`.
This is flawed, because the fields can have their content expression overridden - in fact we will need to override it to something like `nonKeyTakeawaysElement+` in order to prevent a key takeaway element being pasted into another a key takeaway element.
This PR uses the stable "nested-element-field" group that should appear in `nestedFields` as an identifier for our workaround to use. In the long run we'll want to fix the route cause of the `nestedElement` `fieldView` update bug that caused the join issue, rather than relying on this workaround.
n.b. …

Identify nestedElement fields even if their content expression is overridden

---

.changeset/loud-years-care.md
package.json
src/plugin/fieldViews/RichTextFieldView.ts
src/plugin/fieldViews/TextFieldView.ts
src/plugin/helpers/keymap.ts
yarn.lock

_co-authored-by_: @Divs-B 
Ensure that the editor scrolls to the focused field, not the top of the element, when undoing or redoing in text editor fields.
This makes use of a change that [@Divs-B requested in prosemirror-history](
https://github.com/ProseMirror/prosemirror/issues/1451) to provide a way of triggering a history command without a scroll side effect 🎉 
|Before|After|
|--|--|
|![scroll-incorrect](https://github.com/guardian/prosemirror-elements/assets/7767575/37a4d2ad-be00-44f4-a4ed-170cf8a6ed1f)|![scroll-correct](https://github.com/guardian/prosemirror-elements/assets/7767575/ef7cc171-99c0-4382-aae5-11d529bc811b)|
Running locally, have a play with undoing text changes within a text or rich text field. Does the scroll behaviour work as expected?
It'd be nice to include an …

Scroll to focused field, not top of element, when calling history commands in text editor fields

---

src/editorial-source-components/Editor.ts
src/renderers/react/AltStyleElementWrapper.tsx

Makes some minor tweaks to `nestedElement` field and `altStyle` wrapper to make sure the list element title and content align with the main editor text in Composer. They were once aligned but there has been some drift.
| --- | --- |
| ![image](https://github.com/guardian/prosemirror-elements/assets/34686302/1385e717-8b8a-4658-b33b-0ec4eb5dedd0) | ![image](https://github.com/guardian/prosemirror-elements/assets/34686302/d753314f-8d30-4181-928f-81399f3cd6e0) |
1. Use `yarn yalc` in this repo to publish prosemirror-elements locally.
2. Use it in the composer directory of flexible-content with `yalc add @guardian/prosemirror-elements`
3. Create one of the list elements and check out the alignment.

Make list element title and content fields align with body in Composer

---

.changeset/curvy-dryers-serve.md
cypress/helpers/editor.ts
src/elements/demo-image/DemoImageElement.tsx
src/plugin/nodeSpec.ts

Do not coerce HTML nodes without field attributes to a field value of `{}`. This has been causing problems in flexible-content with recipe elements, which often contain optional fields that should be `undefined`. When they instead become `{}`, the rendering code throws an error.
Also removes a redundant code path where we deserialise field values from an element node. Element nodes don't contain fields, so this step isn't required. Because the `fields` attr is not specified in the Element `NodeSpec`, they were never added anyway.
The integration test should verify the change:
- Before the fix in 81bccb5f534b3b442aa64000b97f153e5bb14b84, a field that is undefined by default will receive a value of `{}` when it is deserialised from HTML, and the test with the additional field …

Do not coerce HTML nodes without field attributes to a field value of `{}`

---

.changeset/chilled-ravens-run.md
src/editorial-source-components/Editor.ts
src/elements/alt-style/AltStyleElementForm.tsx

Co-authored with @simonbyford.
We thought we'd have another pop at this to see if we could avoid the side effects in https://github.com/guardian/flexible-content/pull/4704
This time around, we've used outlines rather than borders to avoid layout shifts when we apply the styles, and to make sure validation and focus states are always 'above' the existing borders.
Pull this branch into composer locally with `yalc` and check that this is working properly in one of the list elements.

Remove double border between nested fields and text fields

---

cypress/helpers/editor.ts
docs/quick-start.md
src/editorial-source-components/DemoFieldWrapper.tsx
src/editorial-source-components/DemoInputHeading.tsx
src/elements/alt-style/AltStyleElementForm.tsx
src/elements/callout/CalloutTable.tsx
src/elements/cartoon/CartoonForm.tsx
src/elements/code/CodeElementForm.tsx
src/elements/demo-image/DemoImageElementForm.tsx
src/elements/deprecated/DeprecatedForm.tsx
src/elements/embed/EmbedForm.tsx
src/elements/helpers/Preview.tsx
src/elements/image/ImageElementForm.tsx
src/elements/interactive/InteractiveForm.tsx
src/elements/membership/MembershipForm.tsx
src/elements/pullquote/PullquoteForm.tsx
src/elements/recipe/RecipeElementForm.tsx
src/elements/standard/StandardForm.tsx
src/renderers/react/__tests__/createReactElementSpec.spec.tsx

These two components (`FieldWrapper` and `InputHeading`) are now [directly](https://github.com/guardian/flexible-content/blob/5dc2e938a6a285e4528bb5c4c4fb140ba4386956/composer/src/js/components/elements/FieldWrapper.tsx#L18) [implemented](https://github.com/guardian/flexible-content/blob/5dc2e938a6a285e4528bb5c4c4fb140ba4386956/composer/src/js/components/elements/InputHeading.tsx#L34) in Composer, and the elements in Composer use those implementations, but there are mostly identically implementations within `prosemirror-elements` too. 
This PR renames the versions used internally in `prosemirror-elements` because it's currently very easy to be tripped up by mistaking them for the one implemented in Composer.
Run the demo locally according to the instructions in the readme and check if all …

Rename FieldWrapper and InputHeading to Demo[ClassName] to avoid ambiguity

---

src/elements/alt-style/AltStyleElementForm.tsx
src/index.ts

Exports the required styles and controls for [this PR ](https://github.com/guardian/flexible-content/pull/4728) adding event-level controls for timelines.
Test the composer PR, you should be able to import these and add a new event to a timeline section.

Exported required styles and controls for timeline element

---

src/editorial-source-components/Editor.ts
src/index.ts

This exports the `AltStyleElementWrapper` for use in the `TimelineForm` in Composer. We may want to move this to Composer in the long run, but I'm leaving that for a future optimisation.
It also adds a `flex-grow` style to ProsemirrorFields, i.e. text, rich text and nested. This won't affect most uses but will cause the text fields to fill their horizontal space in a flex layout.
This should be a no-op, but you can test locally with my current branch on Composer:
https://github.com/guardian/flexible-content/compare/main...rm/alt-style-timeline

Support alt styles for Timelines

---

.changeset/wicked-goats-glow.md
src/renderers/react/WrapperControls.tsx

For the timeline element, we want to add event addition controls under the event, rather than in the RightActionPanel.
This PR therefore makes the `addChildAfter` value optional, and hides the corresponding `+` button if `addChildAfter` is falsy.
Use via yalc in this flexible-content PR: https://github.com/guardian/flexible-content/pull/4750/files

Make addChildAfter optional in RightActionControls

---

.changeset/metal-dots-bow.md
src/plugin/helpers/prosemirror.ts

Before this PR, moving elements **up** past a list element was a dangerous pursuit, sometimes even deadly. 
1. If your list element had content, the element moving up would jump into the list element. This is not desired: I think we want the element to move _past_ the list element[^1]. 
https://github.com/guardian/prosemirror-elements/assets/40991816/caff134f-b9f2-4424-bd4e-5876641fb0b0
2. If your list element was empty, the element moving up would get deleted. Also not desired, you would think.
https://github.com/guardian/prosemirror-elements/assets/40991816/0dcfa31e-f84e-4c5a-a983-79367e479615
So what's going on? And why is it only affecting elements moved up?
When moving an element, we search for the next node along in the document to help calculate where to move our element. 
When …

Fix element movement near list elements

---

src/plugin/plugin.ts

_co-authored-by: @rhystmills_  - who is responsible for anything untrue in the following PR description:
Currently, some inner editors (e.g. one of our text fields), hand responsibility for certain commands to the outer editor - notably the `nestedElementField`, which passes events to the outer editor so that it can handle undo, formatting, and other commands. As part of these commands, the outer editor calls `scrollIntoView` - which has led to a bug.
This behaviour hasn't caused problems until now - the only pre-existing fields that have formatting options have their own menu plugins (e.g. the caption in image elements), so don't need to hand control to the outer editor. There was [a PR to specifically handle this problem for history](https://github.com/guardian/prosemirror-elements/pull/ …

Have plugin handle scrollToSelection events when they occur within elements

---

yarn.lock

Imported via ts-loader, so fixed by running `yarn upgrade ts-loader`
Prototype pollution vulnerability in function parseQuery in parseQuery.js in webpack loader-utils prior to version 2.0.3 via the name variable in parseQuery.js.

Bump loader-utils

---

src/plugin/__tests__/plugin.spec.tsx
src/plugin/field.ts
src/plugin/fieldViews/FieldView.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/TextFieldView.spec.ts
src/plugin/plugin.ts

In prosemirror-elements, elements are a collection of fields representing user-editable data. Most logic managing these fields is in the relevant `FieldView`. Text fields are all based on `ProseMirrorFieldView`, via implementations that extend it, e.g. `TextFieldView`. These contain instances of ProseMirror ('inner editors'), and the 'outer editor' (the editor that contains the element) delegates control of certain actions to the 'inner editor' managed by the FieldView.
Currently, two kinds of changes from the outer editor can cause changes in the field view:
1. Changes to the nodes that the inner editor manages:
2. Changes to `Decorations` that affect the range covered by the field view.
However, if the selection is updated by the outer editor, the selection within a relevant field is …

Update inner selection when outer selection updates selection within a text field

---

.changeset/polite-beds-matter.md

Release a changeset for:
https://github.com/guardian/prosemirror-elements/pull/400 - inner selection handling, to solve F10 bug in Composer
https://github.com/guardian/prosemirror-elements/pull/402 - bump loader-utils to solve vulnerability

Add changeset for selection handling in inner editor of ProseMirrorFieldView

---

cypress/helpers/editor.ts
cypress/tests/ImageElement.cy.ts
src/plugin/field.ts
src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/TextFieldView.spec.ts
src/plugin/plugin.ts

We have encountered a few bugs related to the interaction of nested fields with notes from [@guardian/prosemirror-noting](https://github.com/guardian/prosemirror-noting/) - specifically:
1. Typing in the first or final character of a note doesn't extend it
2. Pasting into a note doesn't apply the note mark to the pasted characters
3. Moving over the note boundary via key presses skips a character
This PR fixes these issues by making some changes to the `ProsemirrorFieldView`:
1. Passes in `storedMarks` defined by the outer editor to the inner editor, applying them on the next transaction in the inner editor. The note extension functionality is managed by `storedMarks`, rather than by setting an `inclusive` attribute on the mark, as we see with something like `strong` or `em` marks. Until …

Fix prosemirror-noting bugs by passing storedMarks to inner editor, and passing up paste meta

---

.changeset/twelve-peaches-allow.md

Add changeset for https://github.com/guardian/prosemirror-elements/pull/410 so that we can release it.

Add changeset for recent fix supporting storedMarks in text fields

---

src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/TextFieldView.spec.ts

Fixes an error where backwards selections that extend beyond a field are passed into the field view, causing range errors.
The errors are largely harmless – they're a no-op on the state and do not halt the outer editor – but they're causing some noise in [our downstream CMS's error reporting.](https://the-guardian.sentry.io/issues/5384237869/?project=26737&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0&utc=true)
There's a question as to whether fields should be aware of selections that cover them entirely. I don't think we've seen a use case yet, but we could map and clamp the selection values, rather than just ignoring, if we wanted that behaviour.
- The new unit tests should pass. The commit history shows the failure, …

Fix selection error when backwards selections cover fields

---

src/plugin/fieldViews/ProseMirrorFieldView.ts
src/plugin/fieldViews/__tests__/TextFieldView.spec.ts

This PR modifies the `ProsemirrorFieldView` so that it passes `storedMarks` to the outer editor (the editor that is using the `prosemirror-elements` plugin).
In `updateOuterEditor`, we already updated the outer editor's state with any [steps](https://prosemirror.net/docs/ref/#transform.Steps) (representing node changes) and selection changes from the inner editor's transaction so that the outer editor would reflect state changes in the inner editor.
However, we weren't updating the outer editor's `storedMarks` when an inner editor set them. This led to a bug with our `richText` field editor menu in certain contexts[^1], where a transaction from the outer editor would immediately nullify `storedMarks` set by the inner editor. This happened when clicking on mark buttons like `bold` or …

Pass storedMarks from inner editors to outer editor

---

src/plugin/plugin.ts

This removes a [workaround](https://github.com/guardian/prosemirror-elements/pull/365) that meant elements containing `nestedFields` were updated any time a transaction occurred in the outer editor.
These elements should now only be updated when relevant information changes (their content, decorations, or the shared storedMarks).
The workaround was introduced due to a problem with the 'zipRoot' plugin in flexible-content, which adds empty text elements between other elements, the merges them when the intermediate elements are deleted. An example of that bug can be found in this PR: https://github.com/guardian/flexible-content/pull/4645
It looks like we have fixed the underlying issue since we introduced the workaround, as, testing locally with this branch - the `zipRoot` behaviour now …

Remove field update workaround for elements containing nested fields

---

cypress/tests/ImageElement.cy.ts

This PR removes a flaky test, because it frequently fails in CI.
The test checks that fields with `maxRows` set don't reach the max (implied) height unless there is enough text to fill the maximum number of rows specified.
I've spent some time attempting to fix the test, but ultimately I don't think the test is valuable enough to justify more time spent, so I've removed it instead. It's been difficult to debug because it never fails for me locally, only in CI. The fact the test (falsely) fails in CI regularly means manually re-running the build/CI process when PRs are merged which affects agility on other changes.
This should be a no-op - all the other tests should pass in CI.

Remove flaky test, because it frequently causes problems in CI

---

package.json
yarn.lock

Bump `webpack-dev-server` to solve vulnerability introduced via http-proxy-middleware
`webpack-dev-server` is a dev dependency used to run local dev servers.
1. Run `./script/setup.sh` from the root directory to set up the application, including the nginx mappings that make the local https://prosemirror-elements.local.dev-gutools.co.uk/ url work.
2. Ensure the javascript dependencies are up to date by running `yarn`.
3. Run `yarn start` to start the local server. Does it work?
The dependency is bumped and the dev server still runs.

Bump webpack-dev-server

---

.changeset/sixty-pumpkins-jam.md
cypress/helpers/editor.ts
cypress/tests/ElementWrapper.cy.ts
src/plugin/helpers/__tests__/prosemirror.spec.ts
src/plugin/helpers/prosemirror.ts

At the moment, we add a decoration for every parent element node each time the document changes, to force our element NodeViews to rerender.  Adding decorations is the approach recommended by the library author [(here)](https://discuss.prosemirror.net/t/force-nodes-of-specific-type-to-re-render/2480/10).
Normally, NodeViews would only rerender when their content, internal selection or decorations had changed — but we need to respond to all document changes, regardless of whether they touch the relevant node, to update the element movement UI, the buttons of which are disabled when movement is not possible.
However, forcing rerenders for each element on each change isn't ideal, because in documents with large numbers of elements, ProseMirror has to manage large numbers of decorations, and …

Do not render decorations unless necessary

---

demo/helpers.ts
demo/index.ts
src/plugin/__tests__/element.spec.ts
src/plugin/__tests__/nodeSpec.spec.ts
src/plugin/helpers/prosemirror.ts
src/plugin/nodeSpec.ts

_co-authored-with: @SHession_
At the moment, we're dropping whitespace when we parse elements per HTML's rules ([handy MDN docs.](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace)) This puts us in a situation where we can persist whitespace into elements fields, but cannot remove it — because it's not present to remove.
This PR passes `preserveWhitespace: true` to the ProseMirror methods responsible for parsing element data into ProseMirror nodes, which does what it says on the tin. It was previously set to `false` as what I suspect was an unintended default in the PR that changed it (https://github.com/guardian/prosemirror-elements/pull/129).
- The new unit test should pass.
- Open a document in the sandbox, add an element, and add whitespace. Refresh the …

fix: Preserve whitespace in rich text nodes on parse
