guardian/prosemirror-elements

- embeds/image/ImageEmbed.js
- embeds/image/plugin.js
- index.js
Add some extra functionality to images.
> Adds some config to the image embed and demos how easy it is to change

- README.md
- package.json
- yarn.lock
This PR makes a couple of improvements based on my setup experience of the project. Firstly, it adds a small README we can add to as we go. Secondly, it fixes a warning with the build by updating ''babel-preset-preact". Finally, it adds "@babel/core" which parcel automatically adds to the dev dependencies. 
Setting up the project from a clean version should be straightforward and issue free.
> Improve setup

- README.md
Adds testing information in the repository README.
> Include testing information in the README

- cypress.json
- cypress/helpers/editor.ts
- cypress/tests/ImageElement.spec.ts
- demo/index.html
- demo/style.css
- nginx/dev-nginx.yaml
- package.json
- src/__tests__/element.spec.ts
- src/elements/image/ImageElement.tsx
- src/elements/image/element.tsx
- src/helpers.ts
- src/index.ts
- src/types/Element.ts
- webpack.config.js
This PR adds a new image selector field to the existing custom field. The image selector allows a user to pick an image from the Grid and retain the necessary information within the field node's attributes. 
This change adds a `Props` type parameter to the custom field view, allowing a consumer to specify additional properties that are required for rendering the field correctly. In this case, it's used to pass the field image select and crop callback methods which trigger an iframe and provide a function to call with the chosen image data.
The iframe behaviour is facsimile of the `flexible-content` image selection integration and provides broadly the same functionality although implemented a bit differently. This has also meant we need to use dex-nginx so the panda auth will work …
> Add image select field

- README.md
_co-authored by: @dskamiotis_
Updates the readme re: feedback from @dskamiotis.
Adds a brief description of the project to the top of the readme. We'd like to add:
- an example field declaration
- an example field component
- a gif of the field in action
To demonstrate the plugin in action, but this will hopefully do as a starter.
Are the new additions useful?
> Update readme re: Demetrios' feedback

- cypress/tests/Editor.spec.ts
- cypress/tests/ElementWrapper.spec.ts
- cypress/tests/ImageElement.spec.ts
- demo/collab/CollabServer.ts
- demo/index.ts
#52 introduced a bug – it stopped us saving content locally! oh no :(
This fixes that, and adds a test for it.
The automated tests should pass.
Whilst running the demo, make a change to the editor state in any editor, and refresh the browser page. Does the state persist after a refresh?
> Save state correctly

- cypress/tests/ElementWrapper.spec.ts
- demo/helpers.ts
- demo/index.ts
- src/elements/demo-image/DemoImageElement.tsx
- src/elements/demo-image/DemoImageElementForm.tsx
- src/index.ts
Renames image element to demo image element. This PR is branched from `sh-ds/create-image-element` to avoid merge conflicts in the future.
This change should be a no-op and work and compile as before.
> Rename image element to demo image element

- cypress.json
Disable Cypress videos by default in an attempt to speed up the CI process. Based on a previous build, this could save ~30 seconds.
Edit: Running these test for this PR, was ~60 seconds quick than for #80.
Run Cypress tests in CI.
> perf: Disable Cypress videos by default to speed-up CI

- src/elements/code/CodeElementForm.tsx
- src/elements/code/CodeElementSpec.tsx
Restores a few changes lost whilst merging #92. See that PR for changes.
> fix: Restore code element changes lost in merge

- src/elements/pullquote/PullquoteForm.tsx
- src/elements/pullquote/PullquoteSpec.tsx
Reverts guardian/prosemirror-elements#114
> Revert "fix: Update property names to match interface expected by Composer"

- README.md
Add note to readme to ensure nginx is running.
> docs: Mention that nginx needs to be running

- src/elements/image/ImageElement.tsx
- src/elements/image/__tests__/imageElementDataTransformer.spec.ts
- src/elements/image/imageElementDataTransformer.ts
Makes the photographer field absent when empty.
TBC.
> fix: Make photographer field absent on empty

- src/index.ts
Export the interactive element along with the existing elements, to be consumed in [flexible-content](https://github.com/guardian/flexible-content).
> feat: Export interactive element

- demo/index.ts
- demo/sampleElements.ts
- src/elements/form/FormElementForm.tsx
- src/elements/form/FormElementSpec.tsx
- src/elements/form/formTransformer.ts
- src/elements/helpers/__tests__/fixtures/form.json
- src/elements/helpers/__tests__/fixtures/index.ts
- src/elements/helpers/__tests__/transformFixtures.spec.ts
- src/elements/helpers/transform.ts
- src/index.ts
- Adds the form element to prosemirror elements based on the flexible-content version
- spec and form for form element
- button to demo page which creates form element with sample data
- Transformer functions transformElementIn and transformElementOut to manipulate data to and from the shape required by the form element spec
- fixture tests for the form element
- Run prosemirror-elements locally 
- Add a form element with "Add Form" button
Flexible content version of form element in Composer
PME Form Element
An example of a form element in an article
> feat: Add form element

- README.md
- docs/quick-start.md
We do not have a general quick start guide to help all users of prosemirror-elelements to quickly and easily create an element.
Check the doc in its markdown form for both structure and content for accuracy :)
Checked the layout in https://dillinger.io/
> chore: add readme quick start

- demo/index.ts
- src/elements/callout/Callout.tsx
co-authored by @abeddow91  & @marjisound 
Adds an applyTag handler to the callout component properties and passes the tag to this function. The implementation details of this function will be decided by the consumer. 
This has been tested locally using demo data which logs the tag.
> feat(callout): add applyTag handler

- README.md
- script/setup.sh
This adds a setup.sh script to make it quicker for developers to get this project up and running on their local machines
> docs: Add a setup script

- .changeset/fluffy-ears-juggle.md
Add changeset for the `nestedElementField`, which will cause a PR to open which will release that change to npm.
> Add changeset for the nested field

- .changeset/breezy-birds-arrive.md
Changeset for #334. Merging this will release the changes.
> Release repeater child node controls

- .changeset/little-wasps-tan.md
Get changeset to do a PR for changes introduced in:
https://github.com/guardian/flexible-content/pull/4678
> Add changeset for spacing commit

- .changeset/violet-adults-cross.md
Get changeset to do a PR for changes introduced in: https://github.com/guardian/prosemirror-elements/pull/385/files
> Add changeset for exports required by timeline element

- .changeset/clean-balloons-chew.md
Trigger release for:
- exporting `AltStyleWrapper`
- adding `flex-grow` to text fields so that they fill available space in flex layouts
> Trigger release

- .changeset/quiet-meals-rush.md
Trigger release PR for:
- https://github.com/guardian/prosemirror-elements/pull/397
- https://github.com/guardian/prosemirror-elements/pull/394
> Add changeset for recent PRs

- .changeset/tame-cows-greet.md
> Add changeset

- .changeset/empty-keys-attack.md
**Releases:**
- https://github.com/guardian/prosemirror-elements/pull/417
- https://github.com/guardian/prosemirror-elements/pull/418
> Add changeset for rich text bugfixes
